<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetUserInfo.proto

namespace Dstore\Engine\Mi_GetUserInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.mi_GetUserInfo.Response.Row</code>
 */
class Response_Row extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 row_id = 10000;</code>
     */
    private $row_id = 0;
    /**
     * <pre>
     * ID des im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), dessen Name mit dem Datenbank-Benutzernamen desjenigen, der diese Prozedur aufruft, übereinstimmt
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10001;</code>
     */
    private $user_id = null;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\MiGetUserInfo::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function getRowId()
    {
        return $this->row_id;
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    /**
     * <pre>
     * ID des im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), dessen Name mit dem Datenbank-Benutzernamen desjenigen, der diese Prozedur aufruft, übereinstimmt
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10001;</code>
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * <pre>
     * ID des im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), dessen Name mit dem Datenbank-Benutzernamen desjenigen, der diese Prozedur aufruft, übereinstimmt
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10001;</code>
     */
    public function setUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->user_id = $var;
    }

}

