<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetSettings_Ad.proto

namespace Dstore\Engine\Mi_GetSettings_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.mi_GetSettings_Ad.Response.Row</code>
 */
class Response_Row extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 row_id = 10000;</code>
     */
    private $row_id = 0;
    /**
     * <pre>
     * Name des Benutzers "UserID"
     * </pre>
     *
     * <code>.dstore.values.StringValue user_name = 10001;</code>
     */
    private $user_name = null;
    /**
     * <pre>
     * ID eines im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), zu dem "Value" zum Schlüssel "KeyVariable" hinterlegt ist.Anmerkung: Es gibt einen speziellen Benutzer mit der ID "-1", durch den GLOBALE Einstellungen gekennzeichnet werden.
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10002;</code>
     */
    private $user_id = null;
    /**
     * <pre>
     * Der für den Benutzer "UserID" zum Schlüssel "KeyVariable" hinterlegte Wert
     * </pre>
     *
     * <code>.dstore.values.StringValue value = 10003;</code>
     */
    private $value = null;
    /**
     * <pre>
     * Ein Schlüssel (z.B. "dStore-Version"). Mögliche Werte : siehe Rückgabemenge von " do_GetSettingsDescriptions_Ad 'Settings' "
     * </pre>
     *
     * <code>.dstore.values.StringValue key_variable = 10004;</code>
     */
    private $key_variable = null;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\MiGetSettingsAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function getRowId()
    {
        return $this->row_id;
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    /**
     * <pre>
     * Name des Benutzers "UserID"
     * </pre>
     *
     * <code>.dstore.values.StringValue user_name = 10001;</code>
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * <pre>
     * Name des Benutzers "UserID"
     * </pre>
     *
     * <code>.dstore.values.StringValue user_name = 10001;</code>
     */
    public function setUserName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->user_name = $var;
    }

    /**
     * <pre>
     * ID eines im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), zu dem "Value" zum Schlüssel "KeyVariable" hinterlegt ist.Anmerkung: Es gibt einen speziellen Benutzer mit der ID "-1", durch den GLOBALE Einstellungen gekennzeichnet werden.
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10002;</code>
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * <pre>
     * ID eines im "dStore" registrierten Benutzers (aus der Tabelle "UserInfo"), zu dem "Value" zum Schlüssel "KeyVariable" hinterlegt ist.Anmerkung: Es gibt einen speziellen Benutzer mit der ID "-1", durch den GLOBALE Einstellungen gekennzeichnet werden.
     * </pre>
     *
     * <code>.dstore.values.IntegerValue user_id = 10002;</code>
     */
    public function setUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->user_id = $var;
    }

    /**
     * <pre>
     * Der für den Benutzer "UserID" zum Schlüssel "KeyVariable" hinterlegte Wert
     * </pre>
     *
     * <code>.dstore.values.StringValue value = 10003;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <pre>
     * Der für den Benutzer "UserID" zum Schlüssel "KeyVariable" hinterlegte Wert
     * </pre>
     *
     * <code>.dstore.values.StringValue value = 10003;</code>
     */
    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->value = $var;
    }

    /**
     * <pre>
     * Ein Schlüssel (z.B. "dStore-Version"). Mögliche Werte : siehe Rückgabemenge von " do_GetSettingsDescriptions_Ad 'Settings' "
     * </pre>
     *
     * <code>.dstore.values.StringValue key_variable = 10004;</code>
     */
    public function getKeyVariable()
    {
        return $this->key_variable;
    }

    /**
     * <pre>
     * Ein Schlüssel (z.B. "dStore-Version"). Mögliche Werte : siehe Rückgabemenge von " do_GetSettingsDescriptions_Ad 'Settings' "
     * </pre>
     *
     * <code>.dstore.values.StringValue key_variable = 10004;</code>
     */
    public function setKeyVariable(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->key_variable = $var;
    }

}

