<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/om_ClearTrolley_Pu.proto

namespace Dstore\Engine\Om_ClearTrolley_Pu;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.om_ClearTrolley_Pu.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.dstore.values.StringValue unique_id = 1;</code>
     */
    private $unique_id = null;
    /**
     * <code>bool unique_id_null = 1001;</code>
     */
    private $unique_id_null = false;
    /**
     * <code>.dstore.values.BooleanValue insert_into_statistics = 2;</code>
     */
    private $insert_into_statistics = null;
    /**
     * <code>bool insert_into_statistics_null = 1002;</code>
     */
    private $insert_into_statistics_null = false;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\OmClearTrolleyPu::initOnce();
        parent::__construct();
    }

    /**
     * <code>.dstore.values.StringValue unique_id = 1;</code>
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * <code>.dstore.values.StringValue unique_id = 1;</code>
     */
    public function setUniqueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->unique_id = $var;
    }

    /**
     * <code>bool unique_id_null = 1001;</code>
     */
    public function getUniqueIdNull()
    {
        return $this->unique_id_null;
    }

    /**
     * <code>bool unique_id_null = 1001;</code>
     */
    public function setUniqueIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->unique_id_null = $var;
    }

    /**
     * <code>.dstore.values.BooleanValue insert_into_statistics = 2;</code>
     */
    public function getInsertIntoStatistics()
    {
        return $this->insert_into_statistics;
    }

    /**
     * <code>.dstore.values.BooleanValue insert_into_statistics = 2;</code>
     */
    public function setInsertIntoStatistics(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\BooleanValue::class);
        $this->insert_into_statistics = $var;
    }

    /**
     * <code>bool insert_into_statistics_null = 1002;</code>
     */
    public function getInsertIntoStatisticsNull()
    {
        return $this->insert_into_statistics_null;
    }

    /**
     * <code>bool insert_into_statistics_null = 1002;</code>
     */
    public function setInsertIntoStatisticsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->insert_into_statistics_null = $var;
    }

}

