<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/co_GetMessages_Pu.proto

namespace Dstore\Engine\Co_GetMessages_Pu;

require_once('dstore/values.pb.php');
require_once('dstore/engine/message.pb.php');
require_once('dstore/engine/metainformation.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $unique_id = null;
    private $unique_id_null = false;
    private $person_identification_values = null;
    private $person_identification_values_null = false;
    private $community_id = null;
    private $community_id_null = false;
    private $get_new_messages = null;
    private $get_new_messages_null = false;
    private $date_and_time_format = null;
    private $date_and_time_format_null = false;
    private $message_no = null;
    private $message_no_null = false;
    private $max_number_of_rows = null;
    private $max_number_of_rows_null = false;
    private $separator_in_ident_vals = null;
    private $separator_in_ident_vals_null = false;

    public function getUniqueId()
    {
        return $this->unique_id;
    }

    public function setUniqueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->unique_id = $var;
    }

    public function getUniqueIdNull()
    {
        return $this->unique_id_null;
    }

    public function setUniqueIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->unique_id_null = $var;
    }

    public function getPersonIdentificationValues()
    {
        return $this->person_identification_values;
    }

    public function setPersonIdentificationValues(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->person_identification_values = $var;
    }

    public function getPersonIdentificationValuesNull()
    {
        return $this->person_identification_values_null;
    }

    public function setPersonIdentificationValuesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_identification_values_null = $var;
    }

    public function getCommunityId()
    {
        return $this->community_id;
    }

    public function setCommunityId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->community_id = $var;
    }

    public function getCommunityIdNull()
    {
        return $this->community_id_null;
    }

    public function setCommunityIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->community_id_null = $var;
    }

    public function getGetNewMessages()
    {
        return $this->get_new_messages;
    }

    public function setGetNewMessages(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->get_new_messages = $var;
    }

    public function getGetNewMessagesNull()
    {
        return $this->get_new_messages_null;
    }

    public function setGetNewMessagesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_new_messages_null = $var;
    }

    public function getDateAndTimeFormat()
    {
        return $this->date_and_time_format;
    }

    public function setDateAndTimeFormat(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->date_and_time_format = $var;
    }

    public function getDateAndTimeFormatNull()
    {
        return $this->date_and_time_format_null;
    }

    public function setDateAndTimeFormatNull($var)
    {
        GPBUtil::checkBool($var);
        $this->date_and_time_format_null = $var;
    }

    public function getMessageNo()
    {
        return $this->message_no;
    }

    public function setMessageNo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->message_no = $var;
    }

    public function getMessageNoNull()
    {
        return $this->message_no_null;
    }

    public function setMessageNoNull($var)
    {
        GPBUtil::checkBool($var);
        $this->message_no_null = $var;
    }

    public function getMaxNumberOfRows()
    {
        return $this->max_number_of_rows;
    }

    public function setMaxNumberOfRows(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->max_number_of_rows = $var;
    }

    public function getMaxNumberOfRowsNull()
    {
        return $this->max_number_of_rows_null;
    }

    public function setMaxNumberOfRowsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->max_number_of_rows_null = $var;
    }

    public function getSeparatorInIdentVals()
    {
        return $this->separator_in_ident_vals;
    }

    public function setSeparatorInIdentVals(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->separator_in_ident_vals = $var;
    }

    public function getSeparatorInIdentValsNull()
    {
        return $this->separator_in_ident_vals_null;
    }

    public function setSeparatorInIdentValsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->separator_in_ident_vals_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Co_GetMessages_Pu\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $from_community_member_nickname = null;
    private $message_status = null;
    private $message = null;
    private $message_no = null;
    private $message_date_and_time = null;
    private $from_community_member_id = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getFromCommunityMemberNickname()
    {
        return $this->from_community_member_nickname;
    }

    public function setFromCommunityMemberNickname(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->from_community_member_nickname = $var;
    }

    public function getMessageStatus()
    {
        return $this->message_status;
    }

    public function setMessageStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->message_status = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->message = $var;
    }

    public function getMessageNo()
    {
        return $this->message_no;
    }

    public function setMessageNo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->message_no = $var;
    }

    public function getMessageDateAndTime()
    {
        return $this->message_date_and_time;
    }

    public function setMessageDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->message_date_and_time = $var;
    }

    public function getFromCommunityMemberId()
    {
        return $this->from_community_member_id;
    }

    public function setFromCommunityMemberId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->from_community_member_id = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a910c0a306473746f72652f656e67696e652f70726f636564757265732f" .
    "636f5f4765744d657373616765735f50752e70726f746f121f6473746f72" .
    "652e656e67696e652e636f5f4765744d657373616765735f50751a136473" .
    "746f72652f76616c7565732e70726f746f1a1b6473746f72652f656e6769" .
    "6e652f6d6573736167652e70726f746f1a236473746f72652f656e67696e" .
    "652f6d657461696e666f726d6174696f6e2e70726f746f22d1050a0a5061" .
    "72616d6574657273122d0a09756e697175655f696418012001280b321a2e" .
    "6473746f72652e76616c7565732e737472696e6756616c756512170a0e75" .
    "6e697175655f69645f6e756c6c18e9072001280812400a1c706572736f6e" .
    "5f6964656e74696669636174696f6e5f76616c75657318022001280b321a" .
    "2e6473746f72652e76616c7565732e737472696e6756616c7565122a0a21" .
    "706572736f6e5f6964656e74696669636174696f6e5f76616c7565735f6e" .
    "756c6c18ea072001280812310a0c636f6d6d756e6974795f696418032001" .
    "280b321b2e6473746f72652e76616c7565732e696e746567657256616c75" .
    "65121a0a11636f6d6d756e6974795f69645f6e756c6c18eb072001280812" .
    "350a106765745f6e65775f6d6573736167657318042001280b321b2e6473" .
    "746f72652e76616c7565732e626f6f6c65616e56616c7565121e0a156765" .
    "745f6e65775f6d657373616765735f6e756c6c18ec072001280812390a14" .
    "646174655f616e645f74696d655f666f726d617418052001280b321b2e64" .
    "73746f72652e76616c7565732e696e746567657256616c756512220a1964" .
    "6174655f616e645f74696d655f666f726d61745f6e756c6c18ed07200128" .
    "08122f0a0a6d6573736167655f6e6f18062001280b321b2e6473746f7265" .
    "2e76616c7565732e696e746567657256616c756512180a0f6d6573736167" .
    "655f6e6f5f6e756c6c18ee072001280812370a126d61785f6e756d626572" .
    "5f6f665f726f777318072001280b321b2e6473746f72652e76616c756573" .
    "2e696e746567657256616c756512200a176d61785f6e756d6265725f6f66" .
    "5f726f77735f6e756c6c18ef0720012808123b0a17736570617261746f72" .
    "5f696e5f6964656e745f76616c7318082001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756512250a1c736570617261746f" .
    "725f696e5f6964656e745f76616c735f6e756c6c18f0072001280822b404" .
    "0a08526573706f6e736512480a106d6574615f696e666f726d6174696f6e" .
    "18022003280b322e2e6473746f72652e656e67696e652e6d657461696e66" .
    "6f726d6174696f6e2e4d657461496e666f726d6174696f6e122f0a076d65" .
    "737361676518032003280b321e2e6473746f72652e656e67696e652e6d65" .
    "73736167652e4d657373616765123a0a03726f7718042003280b322d2e64" .
    "73746f72652e656e67696e652e636f5f4765744d657373616765735f5075" .
    "2e526573706f6e73652e526f771af0020a03526f77120f0a06726f775f69" .
    "6418904e2001280512430a1e66726f6d5f636f6d6d756e6974795f6d656d" .
    "6265725f6e69636b6e616d6518914e2001280b321a2e6473746f72652e76" .
    "616c7565732e737472696e6756616c756512340a0e6d6573736167655f73" .
    "746174757318924e2001280b321b2e6473746f72652e76616c7565732e69" .
    "6e746567657256616c7565122c0a076d65737361676518934e2001280b32" .
    "1a2e6473746f72652e76616c7565732e737472696e6756616c756512300a" .
    "0a6d6573736167655f6e6f18944e2001280b321b2e6473746f72652e7661" .
    "6c7565732e696e746567657256616c7565123d0a156d6573736167655f64" .
    "6174655f616e645f74696d6518954e2001280b321d2e6473746f72652e76" .
    "616c7565732e74696d657374616d7056616c7565123e0a1866726f6d5f63" .
    "6f6d6d756e6974795f6d656d6265725f696418964e2001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c756542520a1b696f" .
    "2e6473746f72652e656e67696e652e70726f636564757265735a33676f73" .
    "646b2e6473746f72652e64652f656e67696e652f70726f63656475726573" .
    "2f636f5f4765744d657373616765735f5075620670726f746f33"
));

