<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/fo_CopyPosting_Pu.proto

namespace Dstore\Engine\Fo_CopyPosting_Pu;

require_once('dstore/values.pb.php');
require_once('dstore/engine/message.pb.php');
require_once('dstore/engine/metainformation.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $person_identification_values = null;
    private $person_identification_values_null = false;
    private $person_type_id = null;
    private $person_type_id_null = false;
    private $unique_id = null;
    private $unique_id_null = false;
    private $posting_id = null;
    private $posting_id_null = false;
    private $target_forum_id = null;
    private $target_forum_id_null = false;
    private $target_posting_id = null;
    private $target_posting_id_null = false;
    private $keep_author = null;
    private $keep_author_null = false;
    private $include_replies = null;
    private $include_replies_null = false;
    private $include_binaries = null;
    private $include_binaries_null = false;
    private $include_properties = null;
    private $include_properties_null = false;
    private $author = null;
    private $author_null = false;
    private $e_mail_of_author = null;
    private $e_mail_of_author_null = false;
    private $separator_in_ident_vals = null;
    private $separator_in_ident_vals_null = false;

    public function getPersonIdentificationValues()
    {
        return $this->person_identification_values;
    }

    public function setPersonIdentificationValues(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->person_identification_values = $var;
    }

    public function getPersonIdentificationValuesNull()
    {
        return $this->person_identification_values_null;
    }

    public function setPersonIdentificationValuesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_identification_values_null = $var;
    }

    public function getPersonTypeId()
    {
        return $this->person_type_id;
    }

    public function setPersonTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_type_id = $var;
    }

    public function getPersonTypeIdNull()
    {
        return $this->person_type_id_null;
    }

    public function setPersonTypeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_type_id_null = $var;
    }

    public function getUniqueId()
    {
        return $this->unique_id;
    }

    public function setUniqueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->unique_id = $var;
    }

    public function getUniqueIdNull()
    {
        return $this->unique_id_null;
    }

    public function setUniqueIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->unique_id_null = $var;
    }

    public function getPostingId()
    {
        return $this->posting_id;
    }

    public function setPostingId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->posting_id = $var;
    }

    public function getPostingIdNull()
    {
        return $this->posting_id_null;
    }

    public function setPostingIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->posting_id_null = $var;
    }

    public function getTargetForumId()
    {
        return $this->target_forum_id;
    }

    public function setTargetForumId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->target_forum_id = $var;
    }

    public function getTargetForumIdNull()
    {
        return $this->target_forum_id_null;
    }

    public function setTargetForumIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->target_forum_id_null = $var;
    }

    public function getTargetPostingId()
    {
        return $this->target_posting_id;
    }

    public function setTargetPostingId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->target_posting_id = $var;
    }

    public function getTargetPostingIdNull()
    {
        return $this->target_posting_id_null;
    }

    public function setTargetPostingIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->target_posting_id_null = $var;
    }

    public function getKeepAuthor()
    {
        return $this->keep_author;
    }

    public function setKeepAuthor(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->keep_author = $var;
    }

    public function getKeepAuthorNull()
    {
        return $this->keep_author_null;
    }

    public function setKeepAuthorNull($var)
    {
        GPBUtil::checkBool($var);
        $this->keep_author_null = $var;
    }

    public function getIncludeReplies()
    {
        return $this->include_replies;
    }

    public function setIncludeReplies(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->include_replies = $var;
    }

    public function getIncludeRepliesNull()
    {
        return $this->include_replies_null;
    }

    public function setIncludeRepliesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_replies_null = $var;
    }

    public function getIncludeBinaries()
    {
        return $this->include_binaries;
    }

    public function setIncludeBinaries(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->include_binaries = $var;
    }

    public function getIncludeBinariesNull()
    {
        return $this->include_binaries_null;
    }

    public function setIncludeBinariesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_binaries_null = $var;
    }

    public function getIncludeProperties()
    {
        return $this->include_properties;
    }

    public function setIncludeProperties(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->include_properties = $var;
    }

    public function getIncludePropertiesNull()
    {
        return $this->include_properties_null;
    }

    public function setIncludePropertiesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_properties_null = $var;
    }

    public function getAuthor()
    {
        return $this->author;
    }

    public function setAuthor(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->author = $var;
    }

    public function getAuthorNull()
    {
        return $this->author_null;
    }

    public function setAuthorNull($var)
    {
        GPBUtil::checkBool($var);
        $this->author_null = $var;
    }

    public function getEMailOfAuthor()
    {
        return $this->e_mail_of_author;
    }

    public function setEMailOfAuthor(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->e_mail_of_author = $var;
    }

    public function getEMailOfAuthorNull()
    {
        return $this->e_mail_of_author_null;
    }

    public function setEMailOfAuthorNull($var)
    {
        GPBUtil::checkBool($var);
        $this->e_mail_of_author_null = $var;
    }

    public function getSeparatorInIdentVals()
    {
        return $this->separator_in_ident_vals;
    }

    public function setSeparatorInIdentVals(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->separator_in_ident_vals = $var;
    }

    public function getSeparatorInIdentValsNull()
    {
        return $this->separator_in_ident_vals_null;
    }

    public function setSeparatorInIdentValsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->separator_in_ident_vals_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Fo_CopyPosting_Pu\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ac30c0a306473746f72652f656e67696e652f70726f636564757265732f" .
    "666f5f436f7079506f7374696e675f50752e70726f746f121f6473746f72" .
    "652e656e67696e652e666f5f436f7079506f7374696e675f50751a136473" .
    "746f72652f76616c7565732e70726f746f1a1b6473746f72652f656e6769" .
    "6e652f6d6573736167652e70726f746f1a236473746f72652f656e67696e" .
    "652f6d657461696e666f726d6174696f6e2e70726f746f22de080a0a5061" .
    "72616d657465727312400a1c706572736f6e5f6964656e74696669636174" .
    "696f6e5f76616c75657318012001280b321a2e6473746f72652e76616c75" .
    "65732e737472696e6756616c7565122a0a21706572736f6e5f6964656e74" .
    "696669636174696f6e5f76616c7565735f6e756c6c18e907200128081233" .
    "0a0e706572736f6e5f747970655f696418022001280b321b2e6473746f72" .
    "652e76616c7565732e696e746567657256616c7565121c0a13706572736f" .
    "6e5f747970655f69645f6e756c6c18ea0720012808122d0a09756e697175" .
    "655f696418032001280b321a2e6473746f72652e76616c7565732e737472" .
    "696e6756616c756512170a0e756e697175655f69645f6e756c6c18eb0720" .
    "012808122f0a0a706f7374696e675f696418042001280b321b2e6473746f" .
    "72652e76616c7565732e696e746567657256616c756512180a0f706f7374" .
    "696e675f69645f6e756c6c18ec072001280812340a0f7461726765745f66" .
    "6f72756d5f696418052001280b321b2e6473746f72652e76616c7565732e" .
    "696e746567657256616c7565121d0a147461726765745f666f72756d5f69" .
    "645f6e756c6c18ed072001280812360a117461726765745f706f7374696e" .
    "675f696418062001280b321b2e6473746f72652e76616c7565732e696e74" .
    "6567657256616c7565121f0a167461726765745f706f7374696e675f6964" .
    "5f6e756c6c18ee072001280812300a0b6b6565705f617574686f72180720" .
    "01280b321b2e6473746f72652e76616c7565732e626f6f6c65616e56616c" .
    "756512190a106b6565705f617574686f725f6e756c6c18ef072001280812" .
    "340a0f696e636c7564655f7265706c69657318082001280b321b2e647374" .
    "6f72652e76616c7565732e696e746567657256616c7565121d0a14696e63" .
    "6c7564655f7265706c6965735f6e756c6c18f0072001280812350a10696e" .
    "636c7564655f62696e617269657318092001280b321b2e6473746f72652e" .
    "76616c7565732e696e746567657256616c7565121e0a15696e636c756465" .
    "5f62696e61726965735f6e756c6c18f1072001280812370a12696e636c75" .
    "64655f70726f70657274696573180a2001280b321b2e6473746f72652e76" .
    "616c7565732e696e746567657256616c756512200a17696e636c7564655f" .
    "70726f706572746965735f6e756c6c18f20720012808122a0a0661757468" .
    "6f72180b2001280b321a2e6473746f72652e76616c7565732e737472696e" .
    "6756616c756512140a0b617574686f725f6e756c6c18f307200128081234" .
    "0a10655f6d61696c5f6f665f617574686f72180c2001280b321a2e647374" .
    "6f72652e76616c7565732e737472696e6756616c7565121e0a15655f6d61" .
    "696c5f6f665f617574686f725f6e756c6c18f40720012808123b0a177365" .
    "70617261746f725f696e5f6964656e745f76616c73180d2001280b321a2e" .
    "6473746f72652e76616c7565732e737472696e6756616c756512250a1c73" .
    "6570617261746f725f696e5f6964656e745f76616c735f6e756c6c18f507" .
    "2001280822d9010a08526573706f6e736512480a106d6574615f696e666f" .
    "726d6174696f6e18022003280b322e2e6473746f72652e656e67696e652e" .
    "6d657461696e666f726d6174696f6e2e4d657461496e666f726d6174696f" .
    "6e122f0a076d65737361676518032003280b321e2e6473746f72652e656e" .
    "67696e652e6d6573736167652e4d657373616765123a0a03726f77180420" .
    "03280b322d2e6473746f72652e656e67696e652e666f5f436f7079506f73" .
    "74696e675f50752e526573706f6e73652e526f771a160a03526f77120f0a" .
    "06726f775f696418904e2001280542520a1b696f2e6473746f72652e656e" .
    "67696e652e70726f636564757265735a33676f73646b2e6473746f72652e" .
    "64652f656e67696e652f70726f636564757265732f666f5f436f7079506f" .
    "7374696e675f5075620670726f746f33"
));

