<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetCurrentProcesses_Ad.proto

namespace Dstore\Engine\Mi_GetCurrentProcesses_Ad;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $server_process_id = null;
    private $server_process_id_null = false;

    public function getServerProcessId()
    {
        return $this->server_process_id;
    }

    public function setServerProcessId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->server_process_id = $var;
    }

    public function getServerProcessIdNull()
    {
        return $this->server_process_id_null;
    }

    public function setServerProcessIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->server_process_id_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Mi_GetCurrentProcesses_Ad\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $login_name = null;
    private $host_process = null;
    private $process_status = null;
    private $command = null;
    private $blocking_process_id = null;
    private $server_process_id = null;
    private $d_b_name = null;
    private $program_name = null;
    private $host_name = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getLoginName()
    {
        return $this->login_name;
    }

    public function setLoginName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->login_name = $var;
    }

    public function getHostProcess()
    {
        return $this->host_process;
    }

    public function setHostProcess(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->host_process = $var;
    }

    public function getProcessStatus()
    {
        return $this->process_status;
    }

    public function setProcessStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->process_status = $var;
    }

    public function getCommand()
    {
        return $this->command;
    }

    public function setCommand(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->command = $var;
    }

    public function getBlockingProcessId()
    {
        return $this->blocking_process_id;
    }

    public function setBlockingProcessId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->blocking_process_id = $var;
    }

    public function getServerProcessId()
    {
        return $this->server_process_id;
    }

    public function setServerProcessId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->server_process_id = $var;
    }

    public function getDBName()
    {
        return $this->d_b_name;
    }

    public function setDBName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->d_b_name = $var;
    }

    public function getProgramName()
    {
        return $this->program_name;
    }

    public function setProgramName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->program_name = $var;
    }

    public function getHostName()
    {
        return $this->host_name;
    }

    public function setHostName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->host_name = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ab7080a386473746f72652f656e67696e652f70726f636564757265732f" .
    "6d695f47657443757272656e7450726f6365737365735f41642e70726f74" .
    "6f12276473746f72652e656e67696e652e6d695f47657443757272656e74" .
    "50726f6365737365735f41641a136473746f72652f76616c7565732e7072" .
    "6f746f1a1b6473746f72652f656e67696e652f6d6573736167652e70726f" .
    "746f1a236473746f72652f656e67696e652f6d657461696e666f726d6174" .
    "696f6e2e70726f746f22650a0a506172616d657465727312360a11736572" .
    "7665725f70726f636573735f696418012001280b321b2e6473746f72652e" .
    "76616c7565732e696e746567657256616c7565121f0a167365727665725f" .
    "70726f636573735f69645f6e756c6c18e9072001280822af050a08526573" .
    "706f6e736512480a106d6574615f696e666f726d6174696f6e1802200328" .
    "0b322e2e6473746f72652e656e67696e652e6d657461696e666f726d6174" .
    "696f6e2e4d657461496e666f726d6174696f6e122f0a076d657373616765" .
    "18032003280b321e2e6473746f72652e656e67696e652e6d657373616765" .
    "2e4d65737361676512420a03726f7718042003280b32352e6473746f7265" .
    "2e656e67696e652e6d695f47657443757272656e7450726f636573736573" .
    "5f41642e526573706f6e73652e526f771ae3030a03526f77120f0a06726f" .
    "775f696418904e20012805122f0a0a6c6f67696e5f6e616d6518914e2001" .
    "280b321a2e6473746f72652e76616c7565732e737472696e6756616c7565" .
    "12310a0c686f73745f70726f6365737318924e2001280b321a2e6473746f" .
    "72652e76616c7565732e737472696e6756616c756512330a0e70726f6365" .
    "73735f73746174757318934e2001280b321a2e6473746f72652e76616c75" .
    "65732e737472696e6756616c7565122c0a07636f6d6d616e6418944e2001" .
    "280b321a2e6473746f72652e76616c7565732e737472696e6756616c7565" .
    "12390a13626c6f636b696e675f70726f636573735f696418954e2001280b" .
    "321b2e6473746f72652e76616c7565732e696e746567657256616c756512" .
    "370a117365727665725f70726f636573735f696418964e2001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c7565122d0a08" .
    "645f625f6e616d6518974e2001280b321a2e6473746f72652e76616c7565" .
    "732e737472696e6756616c756512310a0c70726f6772616d5f6e616d6518" .
    "984e2001280b321a2e6473746f72652e76616c7565732e737472696e6756" .
    "616c7565122e0a09686f73745f6e616d6518994e2001280b321a2e647374" .
    "6f72652e76616c7565732e737472696e6756616c7565425a0a1b696f2e64" .
    "73746f72652e656e67696e652e70726f636564757265735a3b676f73646b" .
    "2e6473746f72652e64652f656e67696e652f70726f636564757265732f6d" .
    "695f47657443757272656e7450726f6365737365735f4164620670726f74" .
    "6f33"
));

