<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetApplicationPartsTree_Ad.proto

namespace Dstore\Engine\Mi_GetApplicationPartsTree_Ad;

require_once('dstore/values.pb.php');
require_once('dstore/engine/message.pb.php');
require_once('dstore/engine/metainformation.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $application_part_tree_id = null;
    private $application_part_tree_id_null = false;
    private $get_root_application_parts = null;
    private $get_root_application_parts_null = false;
    private $ids_in_one_id = null;
    private $ids_in_one_id_null = false;
    private $user_id = null;
    private $user_id_null = false;
    private $get_tree_for_user_id = null;
    private $get_tree_for_user_id_null = false;
    private $return_result_set = null;
    private $return_result_set_null = false;
    private $output_into_one_id = null;
    private $output_into_one_id_null = false;
    private $output_into_two_ids = null;
    private $output_into_two_ids_null = false;
    private $max_tree_level = null;
    private $max_tree_level_null = false;
    private $get_root_parts_for_application_id = null;
    private $get_root_parts_for_application_id_null = false;

    public function getApplicationPartTreeId()
    {
        return $this->application_part_tree_id;
    }

    public function setApplicationPartTreeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->application_part_tree_id = $var;
    }

    public function getApplicationPartTreeIdNull()
    {
        return $this->application_part_tree_id_null;
    }

    public function setApplicationPartTreeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->application_part_tree_id_null = $var;
    }

    public function getGetRootApplicationParts()
    {
        return $this->get_root_application_parts;
    }

    public function setGetRootApplicationParts(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->get_root_application_parts = $var;
    }

    public function getGetRootApplicationPartsNull()
    {
        return $this->get_root_application_parts_null;
    }

    public function setGetRootApplicationPartsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_root_application_parts_null = $var;
    }

    public function getIdsInOneId()
    {
        return $this->ids_in_one_id;
    }

    public function setIdsInOneId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->ids_in_one_id = $var;
    }

    public function getIdsInOneIdNull()
    {
        return $this->ids_in_one_id_null;
    }

    public function setIdsInOneIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->ids_in_one_id_null = $var;
    }

    public function getUserId()
    {
        return $this->user_id;
    }

    public function setUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->user_id = $var;
    }

    public function getUserIdNull()
    {
        return $this->user_id_null;
    }

    public function setUserIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->user_id_null = $var;
    }

    public function getGetTreeForUserId()
    {
        return $this->get_tree_for_user_id;
    }

    public function setGetTreeForUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->get_tree_for_user_id = $var;
    }

    public function getGetTreeForUserIdNull()
    {
        return $this->get_tree_for_user_id_null;
    }

    public function setGetTreeForUserIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_tree_for_user_id_null = $var;
    }

    public function getReturnResultSet()
    {
        return $this->return_result_set;
    }

    public function setReturnResultSet(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->return_result_set = $var;
    }

    public function getReturnResultSetNull()
    {
        return $this->return_result_set_null;
    }

    public function setReturnResultSetNull($var)
    {
        GPBUtil::checkBool($var);
        $this->return_result_set_null = $var;
    }

    public function getOutputIntoOneId()
    {
        return $this->output_into_one_id;
    }

    public function setOutputIntoOneId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->output_into_one_id = $var;
    }

    public function getOutputIntoOneIdNull()
    {
        return $this->output_into_one_id_null;
    }

    public function setOutputIntoOneIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->output_into_one_id_null = $var;
    }

    public function getOutputIntoTwoIds()
    {
        return $this->output_into_two_ids;
    }

    public function setOutputIntoTwoIds(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->output_into_two_ids = $var;
    }

    public function getOutputIntoTwoIdsNull()
    {
        return $this->output_into_two_ids_null;
    }

    public function setOutputIntoTwoIdsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->output_into_two_ids_null = $var;
    }

    public function getMaxTreeLevel()
    {
        return $this->max_tree_level;
    }

    public function setMaxTreeLevel(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->max_tree_level = $var;
    }

    public function getMaxTreeLevelNull()
    {
        return $this->max_tree_level_null;
    }

    public function setMaxTreeLevelNull($var)
    {
        GPBUtil::checkBool($var);
        $this->max_tree_level_null = $var;
    }

    public function getGetRootPartsForApplicationId()
    {
        return $this->get_root_parts_for_application_id;
    }

    public function setGetRootPartsForApplicationId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->get_root_parts_for_application_id = $var;
    }

    public function getGetRootPartsForApplicationIdNull()
    {
        return $this->get_root_parts_for_application_id_null;
    }

    public function setGetRootPartsForApplicationIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_root_parts_for_application_id_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Mi_GetApplicationPartsTree_Ad\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $successor_application_part_id = null;
    private $tree_level = null;
    private $successor_application_part = null;
    private $user_name = null;
    private $user_id = null;
    private $has_successors = null;
    private $successor_applic_part_tree_id = null;
    private $application_part_tree_id = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getSuccessorApplicationPartId()
    {
        return $this->successor_application_part_id;
    }

    public function setSuccessorApplicationPartId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->successor_application_part_id = $var;
    }

    public function getTreeLevel()
    {
        return $this->tree_level;
    }

    public function setTreeLevel(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->tree_level = $var;
    }

    public function getSuccessorApplicationPart()
    {
        return $this->successor_application_part;
    }

    public function setSuccessorApplicationPart(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->successor_application_part = $var;
    }

    public function getUserName()
    {
        return $this->user_name;
    }

    public function setUserName(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->user_name = $var;
    }

    public function getUserId()
    {
        return $this->user_id;
    }

    public function setUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->user_id = $var;
    }

    public function getHasSuccessors()
    {
        return $this->has_successors;
    }

    public function setHasSuccessors(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->has_successors = $var;
    }

    public function getSuccessorApplicPartTreeId()
    {
        return $this->successor_applic_part_tree_id;
    }

    public function setSuccessorApplicPartTreeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->successor_applic_part_tree_id = $var;
    }

    public function getApplicationPartTreeId()
    {
        return $this->application_part_tree_id;
    }

    public function setApplicationPartTreeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->application_part_tree_id = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a980f0a3c6473746f72652f656e67696e652f70726f636564757265732f" .
    "6d695f4765744170706c69636174696f6e5061727473547265655f41642e" .
    "70726f746f122b6473746f72652e656e67696e652e6d695f476574417070" .
    "6c69636174696f6e5061727473547265655f41641a136473746f72652f76" .
    "616c7565732e70726f746f1a1b6473746f72652f656e67696e652f6d6573" .
    "736167652e70726f746f1a236473746f72652f656e67696e652f6d657461" .
    "696e666f726d6174696f6e2e70726f746f22b0070a0a506172616d657465" .
    "7273123d0a186170706c69636174696f6e5f706172745f747265655f6964" .
    "18012001280b321b2e6473746f72652e76616c7565732e696e7465676572" .
    "56616c756512260a1d6170706c69636174696f6e5f706172745f74726565" .
    "5f69645f6e756c6c18e90720012808123f0a1a6765745f726f6f745f6170" .
    "706c69636174696f6e5f706172747318022001280b321b2e6473746f7265" .
    "2e76616c7565732e626f6f6c65616e56616c756512280a1f6765745f726f" .
    "6f745f6170706c69636174696f6e5f70617274735f6e756c6c18ea072001" .
    "280812320a0d6964735f696e5f6f6e655f696418032001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c7565121b0a126964" .
    "735f696e5f6f6e655f69645f6e756c6c18eb0720012808122c0a07757365" .
    "725f696418042001280b321b2e6473746f72652e76616c7565732e696e74" .
    "6567657256616c756512150a0c757365725f69645f6e756c6c18ec072001" .
    "280812390a146765745f747265655f666f725f757365725f696418052001" .
    "280b321b2e6473746f72652e76616c7565732e696e746567657256616c75" .
    "6512220a196765745f747265655f666f725f757365725f69645f6e756c6c" .
    "18ed072001280812360a1172657475726e5f726573756c745f7365741806" .
    "2001280b321b2e6473746f72652e76616c7565732e696e74656765725661" .
    "6c7565121f0a1672657475726e5f726573756c745f7365745f6e756c6c18" .
    "ee072001280812370a126f75747075745f696e746f5f6f6e655f69641807" .
    "2001280b321b2e6473746f72652e76616c7565732e696e74656765725661" .
    "6c756512200a176f75747075745f696e746f5f6f6e655f69645f6e756c6c" .
    "18ef072001280812380a136f75747075745f696e746f5f74776f5f696473" .
    "18082001280b321b2e6473746f72652e76616c7565732e626f6f6c65616e" .
    "56616c756512210a186f75747075745f696e746f5f74776f5f6964735f6e" .
    "756c6c18f0072001280812330a0e6d61785f747265655f6c6576656c1809" .
    "2001280b321b2e6473746f72652e76616c7565732e696e74656765725661" .
    "6c7565121c0a136d61785f747265655f6c6576656c5f6e756c6c18f10720" .
    "01280812460a216765745f726f6f745f70617274735f666f725f6170706c" .
    "69636174696f6e5f6964180a2001280b321b2e6473746f72652e76616c75" .
    "65732e696e746567657256616c7565122f0a266765745f726f6f745f7061" .
    "7274735f666f725f6170706c69636174696f6e5f69645f6e756c6c18f207" .
    "2001280822b8050a08526573706f6e736512480a106d6574615f696e666f" .
    "726d6174696f6e18022003280b322e2e6473746f72652e656e67696e652e" .
    "6d657461696e666f726d6174696f6e2e4d657461496e666f726d6174696f" .
    "6e122f0a076d65737361676518032003280b321e2e6473746f72652e656e" .
    "67696e652e6d6573736167652e4d65737361676512460a03726f77180420" .
    "03280b32392e6473746f72652e656e67696e652e6d695f4765744170706c" .
    "69636174696f6e5061727473547265655f41642e526573706f6e73652e52" .
    "6f771ae8030a03526f77120f0a06726f775f696418904e2001280512430a" .
    "1d737563636573736f725f6170706c69636174696f6e5f706172745f6964" .
    "18914e2001280b321b2e6473746f72652e76616c7565732e696e74656765" .
    "7256616c756512300a0a747265655f6c6576656c18924e2001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c7565123f0a1a" .
    "737563636573736f725f6170706c69636174696f6e5f7061727418934e20" .
    "01280b321a2e6473746f72652e76616c7565732e737472696e6756616c75" .
    "65122e0a09757365725f6e616d6518944e2001280b321a2e6473746f7265" .
    "2e76616c7565732e737472696e6756616c7565122d0a07757365725f6964" .
    "18954e2001280b321b2e6473746f72652e76616c7565732e696e74656765" .
    "7256616c756512340a0e6861735f737563636573736f727318964e200128" .
    "0b321b2e6473746f72652e76616c7565732e696e746567657256616c7565" .
    "12430a1d737563636573736f725f6170706c69635f706172745f74726565" .
    "5f696418974e2001280b321b2e6473746f72652e76616c7565732e696e74" .
    "6567657256616c7565123e0a186170706c69636174696f6e5f706172745f" .
    "747265655f696418984e2001280b321b2e6473746f72652e76616c756573" .
    "2e696e746567657256616c7565425e0a1b696f2e6473746f72652e656e67" .
    "696e652e70726f636564757265735a3f676f73646b2e6473746f72652e64" .
    "652f656e67696e652f70726f636564757265732f6d695f4765744170706c" .
    "69636174696f6e5061727473547265655f4164620670726f746f33"
));

