<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_InsertTempdb_OneID.proto

namespace Dstore\Engine\Mi_InsertTempdb_OneID;

require_once('dstore/values.pb.php');
require_once('dstore/engine/message.pb.php');
require_once('dstore/engine/metainformation.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $id_list = null;
    private $id_list_null = false;
    private $delete = null;
    private $delete_null = false;
    private $list_separator = null;
    private $list_separator_null = false;

    public function getIdList()
    {
        return $this->id_list;
    }

    public function setIdList(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->id_list = $var;
    }

    public function getIdListNull()
    {
        return $this->id_list_null;
    }

    public function setIdListNull($var)
    {
        GPBUtil::checkBool($var);
        $this->id_list_null = $var;
    }

    public function getDelete()
    {
        return $this->delete;
    }

    public function setDelete(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->delete = $var;
    }

    public function getDeleteNull()
    {
        return $this->delete_null;
    }

    public function setDeleteNull($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_null = $var;
    }

    public function getListSeparator()
    {
        return $this->list_separator;
    }

    public function setListSeparator(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->list_separator = $var;
    }

    public function getListSeparatorNull()
    {
        return $this->list_separator_null;
    }

    public function setListSeparatorNull($var)
    {
        GPBUtil::checkBool($var);
        $this->list_separator_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Mi_InsertTempdb_OneID\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ada050a346473746f72652f656e67696e652f70726f636564757265732f" .
    "6d695f496e7365727454656d7064625f4f6e6549442e70726f746f122364" .
    "73746f72652e656e67696e652e6d695f496e7365727454656d7064625f4f" .
    "6e6549441a136473746f72652f76616c7565732e70726f746f1a1b647374" .
    "6f72652f656e67696e652f6d6573736167652e70726f746f1a236473746f" .
    "72652f656e67696e652f6d657461696e666f726d6174696f6e2e70726f74" .
    "6f22e5010a0a506172616d6574657273122b0a0769645f6c697374180120" .
    "01280b321a2e6473746f72652e76616c7565732e737472696e6756616c75" .
    "6512150a0c69645f6c6973745f6e756c6c18e90720012808122b0a066465" .
    "6c65746518022001280b321b2e6473746f72652e76616c7565732e626f6f" .
    "6c65616e56616c756512140a0b64656c6574655f6e756c6c18ea07200128" .
    "0812320a0e6c6973745f736570617261746f7218032001280b321a2e6473" .
    "746f72652e76616c7565732e737472696e6756616c7565121c0a136c6973" .
    "745f736570617261746f725f6e756c6c18eb072001280822dd010a085265" .
    "73706f6e736512480a106d6574615f696e666f726d6174696f6e18022003" .
    "280b322e2e6473746f72652e656e67696e652e6d657461696e666f726d61" .
    "74696f6e2e4d657461496e666f726d6174696f6e122f0a076d6573736167" .
    "6518032003280b321e2e6473746f72652e656e67696e652e6d6573736167" .
    "652e4d657373616765123e0a03726f7718042003280b32312e6473746f72" .
    "652e656e67696e652e6d695f496e7365727454656d7064625f4f6e654944" .
    "2e526573706f6e73652e526f771a160a03526f77120f0a06726f775f6964" .
    "18904e2001280542560a1b696f2e6473746f72652e656e67696e652e7072" .
    "6f636564757265735a37676f73646b2e6473746f72652e64652f656e6769" .
    "6e652f70726f636564757265732f6d695f496e7365727454656d7064625f" .
    "4f6e654944620670726f746f33"
));

