<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/om_GetAllowedOrderStates.proto

namespace Dstore\Engine\Om_GetAllowedOrderStates;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $from_order_state_id = null;
    private $from_order_state_id_null = false;
    private $to_order_state_id = null;
    private $to_order_state_id_null = false;
    private $payment_for_shipping_id = null;
    private $payment_for_shipping_id_null = false;
    private $language_id = null;
    private $language_id_null = false;
    private $only_active = null;
    private $only_active_null = false;

    public function getFromOrderStateId()
    {
        return $this->from_order_state_id;
    }

    public function setFromOrderStateId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->from_order_state_id = $var;
    }

    public function getFromOrderStateIdNull()
    {
        return $this->from_order_state_id_null;
    }

    public function setFromOrderStateIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->from_order_state_id_null = $var;
    }

    public function getToOrderStateId()
    {
        return $this->to_order_state_id;
    }

    public function setToOrderStateId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->to_order_state_id = $var;
    }

    public function getToOrderStateIdNull()
    {
        return $this->to_order_state_id_null;
    }

    public function setToOrderStateIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->to_order_state_id_null = $var;
    }

    public function getPaymentForShippingId()
    {
        return $this->payment_for_shipping_id;
    }

    public function setPaymentForShippingId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->payment_for_shipping_id = $var;
    }

    public function getPaymentForShippingIdNull()
    {
        return $this->payment_for_shipping_id_null;
    }

    public function setPaymentForShippingIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->payment_for_shipping_id_null = $var;
    }

    public function getLanguageId()
    {
        return $this->language_id;
    }

    public function setLanguageId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->language_id = $var;
    }

    public function getLanguageIdNull()
    {
        return $this->language_id_null;
    }

    public function setLanguageIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->language_id_null = $var;
    }

    public function getOnlyActive()
    {
        return $this->only_active;
    }

    public function setOnlyActive(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->only_active = $var;
    }

    public function getOnlyActiveNull()
    {
        return $this->only_active_null;
    }

    public function setOnlyActiveNull($var)
    {
        GPBUtil::checkBool($var);
        $this->only_active_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Om_GetAllowedOrderStates\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $to_public_description = null;
    private $to_order_state_id = null;
    private $payment_for_shipping_id = null;
    private $from_order_state_id = null;
    private $from_public_description = null;
    private $shipping_type_id = null;
    private $to_order_state = null;
    private $payment_for_shipping_description = null;
    private $payment_type_id = null;
    private $from_order_state = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getToPublicDescription()
    {
        return $this->to_public_description;
    }

    public function setToPublicDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->to_public_description = $var;
    }

    public function getToOrderStateId()
    {
        return $this->to_order_state_id;
    }

    public function setToOrderStateId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->to_order_state_id = $var;
    }

    public function getPaymentForShippingId()
    {
        return $this->payment_for_shipping_id;
    }

    public function setPaymentForShippingId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->payment_for_shipping_id = $var;
    }

    public function getFromOrderStateId()
    {
        return $this->from_order_state_id;
    }

    public function setFromOrderStateId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->from_order_state_id = $var;
    }

    public function getFromPublicDescription()
    {
        return $this->from_public_description;
    }

    public function setFromPublicDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->from_public_description = $var;
    }

    public function getShippingTypeId()
    {
        return $this->shipping_type_id;
    }

    public function setShippingTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->shipping_type_id = $var;
    }

    public function getToOrderState()
    {
        return $this->to_order_state;
    }

    public function setToOrderState(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->to_order_state = $var;
    }

    public function getPaymentForShippingDescription()
    {
        return $this->payment_for_shipping_description;
    }

    public function setPaymentForShippingDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->payment_for_shipping_description = $var;
    }

    public function getPaymentTypeId()
    {
        return $this->payment_type_id;
    }

    public function setPaymentTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->payment_type_id = $var;
    }

    public function getFromOrderState()
    {
        return $this->from_order_state;
    }

    public function setFromOrderState(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->from_order_state = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a920c0a376473746f72652f656e67696e652f70726f636564757265732f" .
    "6f6d5f476574416c6c6f7765644f726465725374617465732e70726f746f" .
    "12266473746f72652e656e67696e652e6f6d5f476574416c6c6f7765644f" .
    "726465725374617465731a136473746f72652f76616c7565732e70726f74" .
    "6f1a1b6473746f72652f656e67696e652f6d6573736167652e70726f746f" .
    "1a236473746f72652f656e67696e652f6d657461696e666f726d6174696f" .
    "6e2e70726f746f22c1030a0a506172616d657465727312380a1366726f6d" .
    "5f6f726465725f73746174655f696418012001280b321b2e6473746f7265" .
    "2e76616c7565732e696e746567657256616c756512210a1866726f6d5f6f" .
    "726465725f73746174655f69645f6e756c6c18e9072001280812360a1174" .
    "6f5f6f726465725f73746174655f696418022001280b321b2e6473746f72" .
    "652e76616c7565732e696e746567657256616c7565121f0a16746f5f6f72" .
    "6465725f73746174655f69645f6e756c6c18ea0720012808123c0a177061" .
    "796d656e745f666f725f7368697070696e675f696418032001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c756512250a1c" .
    "7061796d656e745f666f725f7368697070696e675f69645f6e756c6c18eb" .
    "072001280812300a0b6c616e67756167655f696418042001280b321b2e64" .
    "73746f72652e76616c7565732e696e746567657256616c756512190a106c" .
    "616e67756167655f69645f6e756c6c18ec072001280812300a0b6f6e6c79" .
    "5f61637469766518052001280b321b2e6473746f72652e76616c7565732e" .
    "626f6f6c65616e56616c756512190a106f6e6c795f6163746976655f6e75" .
    "6c6c18ed072001280822b0060a08526573706f6e736512480a106d657461" .
    "5f696e666f726d6174696f6e18022003280b322e2e6473746f72652e656e" .
    "67696e652e6d657461696e666f726d6174696f6e2e4d657461496e666f72" .
    "6d6174696f6e122f0a076d65737361676518032003280b321e2e6473746f" .
    "72652e656e67696e652e6d6573736167652e4d65737361676512410a0372" .
    "6f7718042003280b32342e6473746f72652e656e67696e652e6f6d5f4765" .
    "74416c6c6f7765644f726465725374617465732e526573706f6e73652e52" .
    "6f771ae5040a03526f77120f0a06726f775f696418904e20012805123a0a" .
    "15746f5f7075626c69635f6465736372697074696f6e18914e2001280b32" .
    "1a2e6473746f72652e76616c7565732e737472696e6756616c756512370a" .
    "11746f5f6f726465725f73746174655f696418924e2001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c7565123d0a177061" .
    "796d656e745f666f725f7368697070696e675f696418934e2001280b321b" .
    "2e6473746f72652e76616c7565732e696e746567657256616c756512390a" .
    "1366726f6d5f6f726465725f73746174655f696418944e2001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c7565123c0a17" .
    "66726f6d5f7075626c69635f6465736372697074696f6e18954e2001280b" .
    "321a2e6473746f72652e76616c7565732e737472696e6756616c75651236" .
    "0a107368697070696e675f747970655f696418964e2001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c756512330a0e746f" .
    "5f6f726465725f737461746518974e2001280b321a2e6473746f72652e76" .
    "616c7565732e737472696e6756616c756512450a207061796d656e745f66" .
    "6f725f7368697070696e675f6465736372697074696f6e18984e2001280b" .
    "321a2e6473746f72652e76616c7565732e737472696e6756616c75651235" .
    "0a0f7061796d656e745f747970655f696418994e2001280b321b2e647374" .
    "6f72652e76616c7565732e696e746567657256616c756512350a1066726f" .
    "6d5f6f726465725f7374617465189a4e2001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756542590a1b696f2e6473746f72" .
    "652e656e67696e652e70726f636564757265735a3a676f73646b2e647374" .
    "6f72652e64652f656e67696e652f70726f636564757265732f6f6d5f4765" .
    "74416c6c6f7765644f72646572537461746573620670726f746f33"
));

