<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/om_GetOrders_Conditions_Ad.proto

namespace Dstore\Engine\Om_GetOrders_Conditions_Ad;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $order_by_column = null;
    private $order_by_column_null = false;
    private $create_valid_order_infos = null;
    private $create_valid_order_infos_null = false;
    private $brutto_sum = null;
    private $brutto_sum_null = false;
    private $currency_id = null;
    private $currency_id_null = false;
    private $quantity_for_one_order_content = null;
    private $quantity_for_one_order_content_null = false;
    private $combination = null;
    private $combination_null = false;
    private $from_date = null;
    private $from_date_null = false;
    private $to_date = null;
    private $to_date_null = false;
    private $order_desc = null;
    private $order_desc_null = false;
    private $date_and_time_format = null;
    private $date_and_time_format_null = false;
    private $include_time = null;
    private $include_time_null = false;
    private $get_info_for_valid_order_content = null;
    private $get_info_for_valid_order_content_null = false;
    private $order_state_list = null;
    private $order_state_list_null = false;
    private $skip_o_having_different_o_states = null;
    private $skip_o_having_different_o_states_null = false;
    private $payment_type_id_list = null;
    private $payment_type_id_list_null = false;
    private $shipping_type_id_list = null;
    private $shipping_type_id_list_null = false;
    private $show_person_characteristics = null;
    private $show_person_characteristics_null = false;
    private $convert_result_to_currency_id = null;
    private $convert_result_to_currency_id_null = false;
    private $convert_result_to_given_currency = null;
    private $convert_result_to_given_currency_null = false;
    private $purchase_order = null;
    private $purchase_order_null = false;
    private $input_nest_level_o_info_conds = null;
    private $input_nest_level_o_info_conds_null = false;
    private $value_separator_i_n_operator = null;
    private $value_separator_i_n_operator_null = false;
    private $country = null;
    private $country_null = false;
    private $language_id = null;
    private $language_id_null = false;
    private $input_nest_level_o_con_info_conds = null;
    private $input_nest_level_o_con_info_conds_null = false;
    private $conds_must_be_fulfilled_for_o_con_id = null;
    private $conds_must_be_fulfilled_for_o_con_id_null = false;
    private $filter_by_node_ids_in_one_id = null;
    private $filter_by_node_ids_in_one_id_null = false;
    private $get_computed_sum = null;
    private $get_computed_sum_null = false;
    private $only_valid_pos_for_computed_sum = null;
    private $only_valid_pos_for_computed_sum_null = false;
    private $order_surch_ids_for_computed_sum = null;
    private $order_surch_ids_for_computed_sum_null = false;

    public function getOrderByColumn()
    {
        return $this->order_by_column;
    }

    public function setOrderByColumn(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->order_by_column = $var;
    }

    public function getOrderByColumnNull()
    {
        return $this->order_by_column_null;
    }

    public function setOrderByColumnNull($var)
    {
        GPBUtil::checkBool($var);
        $this->order_by_column_null = $var;
    }

    public function getCreateValidOrderInfos()
    {
        return $this->create_valid_order_infos;
    }

    public function setCreateValidOrderInfos(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->create_valid_order_infos = $var;
    }

    public function getCreateValidOrderInfosNull()
    {
        return $this->create_valid_order_infos_null;
    }

    public function setCreateValidOrderInfosNull($var)
    {
        GPBUtil::checkBool($var);
        $this->create_valid_order_infos_null = $var;
    }

    public function getBruttoSum()
    {
        return $this->brutto_sum;
    }

    public function setBruttoSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->brutto_sum = $var;
    }

    public function getBruttoSumNull()
    {
        return $this->brutto_sum_null;
    }

    public function setBruttoSumNull($var)
    {
        GPBUtil::checkBool($var);
        $this->brutto_sum_null = $var;
    }

    public function getCurrencyId()
    {
        return $this->currency_id;
    }

    public function setCurrencyId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->currency_id = $var;
    }

    public function getCurrencyIdNull()
    {
        return $this->currency_id_null;
    }

    public function setCurrencyIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->currency_id_null = $var;
    }

    public function getQuantityForOneOrderContent()
    {
        return $this->quantity_for_one_order_content;
    }

    public function setQuantityForOneOrderContent(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->quantity_for_one_order_content = $var;
    }

    public function getQuantityForOneOrderContentNull()
    {
        return $this->quantity_for_one_order_content_null;
    }

    public function setQuantityForOneOrderContentNull($var)
    {
        GPBUtil::checkBool($var);
        $this->quantity_for_one_order_content_null = $var;
    }

    public function getCombination()
    {
        return $this->combination;
    }

    public function setCombination(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->combination = $var;
    }

    public function getCombinationNull()
    {
        return $this->combination_null;
    }

    public function setCombinationNull($var)
    {
        GPBUtil::checkBool($var);
        $this->combination_null = $var;
    }

    public function getFromDate()
    {
        return $this->from_date;
    }

    public function setFromDate(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->from_date = $var;
    }

    public function getFromDateNull()
    {
        return $this->from_date_null;
    }

    public function setFromDateNull($var)
    {
        GPBUtil::checkBool($var);
        $this->from_date_null = $var;
    }

    public function getToDate()
    {
        return $this->to_date;
    }

    public function setToDate(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->to_date = $var;
    }

    public function getToDateNull()
    {
        return $this->to_date_null;
    }

    public function setToDateNull($var)
    {
        GPBUtil::checkBool($var);
        $this->to_date_null = $var;
    }

    public function getOrderDesc()
    {
        return $this->order_desc;
    }

    public function setOrderDesc(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->order_desc = $var;
    }

    public function getOrderDescNull()
    {
        return $this->order_desc_null;
    }

    public function setOrderDescNull($var)
    {
        GPBUtil::checkBool($var);
        $this->order_desc_null = $var;
    }

    public function getDateAndTimeFormat()
    {
        return $this->date_and_time_format;
    }

    public function setDateAndTimeFormat(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->date_and_time_format = $var;
    }

    public function getDateAndTimeFormatNull()
    {
        return $this->date_and_time_format_null;
    }

    public function setDateAndTimeFormatNull($var)
    {
        GPBUtil::checkBool($var);
        $this->date_and_time_format_null = $var;
    }

    public function getIncludeTime()
    {
        return $this->include_time;
    }

    public function setIncludeTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->include_time = $var;
    }

    public function getIncludeTimeNull()
    {
        return $this->include_time_null;
    }

    public function setIncludeTimeNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_time_null = $var;
    }

    public function getGetInfoForValidOrderContent()
    {
        return $this->get_info_for_valid_order_content;
    }

    public function setGetInfoForValidOrderContent(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->get_info_for_valid_order_content = $var;
    }

    public function getGetInfoForValidOrderContentNull()
    {
        return $this->get_info_for_valid_order_content_null;
    }

    public function setGetInfoForValidOrderContentNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_info_for_valid_order_content_null = $var;
    }

    public function getOrderStateList()
    {
        return $this->order_state_list;
    }

    public function setOrderStateList(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->order_state_list = $var;
    }

    public function getOrderStateListNull()
    {
        return $this->order_state_list_null;
    }

    public function setOrderStateListNull($var)
    {
        GPBUtil::checkBool($var);
        $this->order_state_list_null = $var;
    }

    public function getSkipOHavingDifferentOStates()
    {
        return $this->skip_o_having_different_o_states;
    }

    public function setSkipOHavingDifferentOStates(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->skip_o_having_different_o_states = $var;
    }

    public function getSkipOHavingDifferentOStatesNull()
    {
        return $this->skip_o_having_different_o_states_null;
    }

    public function setSkipOHavingDifferentOStatesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->skip_o_having_different_o_states_null = $var;
    }

    public function getPaymentTypeIdList()
    {
        return $this->payment_type_id_list;
    }

    public function setPaymentTypeIdList(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->payment_type_id_list = $var;
    }

    public function getPaymentTypeIdListNull()
    {
        return $this->payment_type_id_list_null;
    }

    public function setPaymentTypeIdListNull($var)
    {
        GPBUtil::checkBool($var);
        $this->payment_type_id_list_null = $var;
    }

    public function getShippingTypeIdList()
    {
        return $this->shipping_type_id_list;
    }

    public function setShippingTypeIdList(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->shipping_type_id_list = $var;
    }

    public function getShippingTypeIdListNull()
    {
        return $this->shipping_type_id_list_null;
    }

    public function setShippingTypeIdListNull($var)
    {
        GPBUtil::checkBool($var);
        $this->shipping_type_id_list_null = $var;
    }

    public function getShowPersonCharacteristics()
    {
        return $this->show_person_characteristics;
    }

    public function setShowPersonCharacteristics(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->show_person_characteristics = $var;
    }

    public function getShowPersonCharacteristicsNull()
    {
        return $this->show_person_characteristics_null;
    }

    public function setShowPersonCharacteristicsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->show_person_characteristics_null = $var;
    }

    public function getConvertResultToCurrencyId()
    {
        return $this->convert_result_to_currency_id;
    }

    public function setConvertResultToCurrencyId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->convert_result_to_currency_id = $var;
    }

    public function getConvertResultToCurrencyIdNull()
    {
        return $this->convert_result_to_currency_id_null;
    }

    public function setConvertResultToCurrencyIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->convert_result_to_currency_id_null = $var;
    }

    public function getConvertResultToGivenCurrency()
    {
        return $this->convert_result_to_given_currency;
    }

    public function setConvertResultToGivenCurrency(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->convert_result_to_given_currency = $var;
    }

    public function getConvertResultToGivenCurrencyNull()
    {
        return $this->convert_result_to_given_currency_null;
    }

    public function setConvertResultToGivenCurrencyNull($var)
    {
        GPBUtil::checkBool($var);
        $this->convert_result_to_given_currency_null = $var;
    }

    public function getPurchaseOrder()
    {
        return $this->purchase_order;
    }

    public function setPurchaseOrder(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->purchase_order = $var;
    }

    public function getPurchaseOrderNull()
    {
        return $this->purchase_order_null;
    }

    public function setPurchaseOrderNull($var)
    {
        GPBUtil::checkBool($var);
        $this->purchase_order_null = $var;
    }

    public function getInputNestLevelOInfoConds()
    {
        return $this->input_nest_level_o_info_conds;
    }

    public function setInputNestLevelOInfoConds(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->input_nest_level_o_info_conds = $var;
    }

    public function getInputNestLevelOInfoCondsNull()
    {
        return $this->input_nest_level_o_info_conds_null;
    }

    public function setInputNestLevelOInfoCondsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->input_nest_level_o_info_conds_null = $var;
    }

    public function getValueSeparatorINOperator()
    {
        return $this->value_separator_i_n_operator;
    }

    public function setValueSeparatorINOperator(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->value_separator_i_n_operator = $var;
    }

    public function getValueSeparatorINOperatorNull()
    {
        return $this->value_separator_i_n_operator_null;
    }

    public function setValueSeparatorINOperatorNull($var)
    {
        GPBUtil::checkBool($var);
        $this->value_separator_i_n_operator_null = $var;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function setCountry(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->country = $var;
    }

    public function getCountryNull()
    {
        return $this->country_null;
    }

    public function setCountryNull($var)
    {
        GPBUtil::checkBool($var);
        $this->country_null = $var;
    }

    public function getLanguageId()
    {
        return $this->language_id;
    }

    public function setLanguageId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->language_id = $var;
    }

    public function getLanguageIdNull()
    {
        return $this->language_id_null;
    }

    public function setLanguageIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->language_id_null = $var;
    }

    public function getInputNestLevelOConInfoConds()
    {
        return $this->input_nest_level_o_con_info_conds;
    }

    public function setInputNestLevelOConInfoConds(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->input_nest_level_o_con_info_conds = $var;
    }

    public function getInputNestLevelOConInfoCondsNull()
    {
        return $this->input_nest_level_o_con_info_conds_null;
    }

    public function setInputNestLevelOConInfoCondsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->input_nest_level_o_con_info_conds_null = $var;
    }

    public function getCondsMustBeFulfilledForOConId()
    {
        return $this->conds_must_be_fulfilled_for_o_con_id;
    }

    public function setCondsMustBeFulfilledForOConId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->conds_must_be_fulfilled_for_o_con_id = $var;
    }

    public function getCondsMustBeFulfilledForOConIdNull()
    {
        return $this->conds_must_be_fulfilled_for_o_con_id_null;
    }

    public function setCondsMustBeFulfilledForOConIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->conds_must_be_fulfilled_for_o_con_id_null = $var;
    }

    public function getFilterByNodeIdsInOneId()
    {
        return $this->filter_by_node_ids_in_one_id;
    }

    public function setFilterByNodeIdsInOneId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->filter_by_node_ids_in_one_id = $var;
    }

    public function getFilterByNodeIdsInOneIdNull()
    {
        return $this->filter_by_node_ids_in_one_id_null;
    }

    public function setFilterByNodeIdsInOneIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->filter_by_node_ids_in_one_id_null = $var;
    }

    public function getGetComputedSum()
    {
        return $this->get_computed_sum;
    }

    public function setGetComputedSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->get_computed_sum = $var;
    }

    public function getGetComputedSumNull()
    {
        return $this->get_computed_sum_null;
    }

    public function setGetComputedSumNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_computed_sum_null = $var;
    }

    public function getOnlyValidPosForComputedSum()
    {
        return $this->only_valid_pos_for_computed_sum;
    }

    public function setOnlyValidPosForComputedSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->only_valid_pos_for_computed_sum = $var;
    }

    public function getOnlyValidPosForComputedSumNull()
    {
        return $this->only_valid_pos_for_computed_sum_null;
    }

    public function setOnlyValidPosForComputedSumNull($var)
    {
        GPBUtil::checkBool($var);
        $this->only_valid_pos_for_computed_sum_null = $var;
    }

    public function getOrderSurchIdsForComputedSum()
    {
        return $this->order_surch_ids_for_computed_sum;
    }

    public function setOrderSurchIdsForComputedSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->order_surch_ids_for_computed_sum = $var;
    }

    public function getOrderSurchIdsForComputedSumNull()
    {
        return $this->order_surch_ids_for_computed_sum_null;
    }

    public function setOrderSurchIdsForComputedSumNull($var)
    {
        GPBUtil::checkBool($var);
        $this->order_surch_ids_for_computed_sum_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Om_GetOrders_Conditions_Ad\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $order_date_and_time = null;
    private $payment_cost = null;
    private $delivery_date_and_time = null;
    private $net_shipping_cost = null;
    private $order_no = null;
    private $netto_sum = null;
    private $last_edited_by_user_id = null;
    private $order_id = null;
    private $brutto_sum = null;
    private $precise_net_shipping_cost = null;
    private $charac_val2_restr_by_pattern = null;
    private $net_sum = null;
    private $valid_content_net_sum = null;
    private $precise_valid_content_net_sum = null;
    private $person_id = null;
    private $payment_type_description = null;
    private $valid_content_brutto_sum = null;
    private $precise_net_sum = null;
    private $position_count = null;
    private $order_state_id = null;
    private $shipping_type_id = null;
    private $person_type_id = null;
    private $precise_computed_gross_sum = null;
    private $has_valid_contents = null;
    private $net_payment_cost = null;
    private $delivery_person_id = null;
    private $shipping_type_description = null;
    private $gross_sum = null;
    private $unit_symbol = null;
    private $precise_net_payment_cost = null;
    private $customer_characteristic_value2 = null;
    private $public_description = null;
    private $currency_id = null;
    private $customer_characteristic_value1 = null;
    private $precise_gross_sum = null;
    private $computed_gross_sum = null;
    private $valid_content_netto_sum = null;
    private $shipping_cost = null;
    private $charac_val1_restr_by_pattern = null;
    private $payment_type_id = null;
    private $precise_valid_content_gross_sum = null;
    private $precise_computed_net_sum = null;
    private $order_state = null;
    private $computed_net_sum = null;
    private $valid_content_gross_sum = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getOrderDateAndTime()
    {
        return $this->order_date_and_time;
    }

    public function setOrderDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->order_date_and_time = $var;
    }

    public function getPaymentCost()
    {
        return $this->payment_cost;
    }

    public function setPaymentCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->payment_cost = $var;
    }

    public function getDeliveryDateAndTime()
    {
        return $this->delivery_date_and_time;
    }

    public function setDeliveryDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->delivery_date_and_time = $var;
    }

    public function getNetShippingCost()
    {
        return $this->net_shipping_cost;
    }

    public function setNetShippingCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->net_shipping_cost = $var;
    }

    public function getOrderNo()
    {
        return $this->order_no;
    }

    public function setOrderNo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->order_no = $var;
    }

    public function getNettoSum()
    {
        return $this->netto_sum;
    }

    public function setNettoSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->netto_sum = $var;
    }

    public function getLastEditedByUserId()
    {
        return $this->last_edited_by_user_id;
    }

    public function setLastEditedByUserId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->last_edited_by_user_id = $var;
    }

    public function getOrderId()
    {
        return $this->order_id;
    }

    public function setOrderId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->order_id = $var;
    }

    public function getBruttoSum()
    {
        return $this->brutto_sum;
    }

    public function setBruttoSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->brutto_sum = $var;
    }

    public function getPreciseNetShippingCost()
    {
        return $this->precise_net_shipping_cost;
    }

    public function setPreciseNetShippingCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_net_shipping_cost = $var;
    }

    public function getCharacVal2RestrByPattern()
    {
        return $this->charac_val2_restr_by_pattern;
    }

    public function setCharacVal2RestrByPattern(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->charac_val2_restr_by_pattern = $var;
    }

    public function getNetSum()
    {
        return $this->net_sum;
    }

    public function setNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->net_sum = $var;
    }

    public function getValidContentNetSum()
    {
        return $this->valid_content_net_sum;
    }

    public function setValidContentNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->valid_content_net_sum = $var;
    }

    public function getPreciseValidContentNetSum()
    {
        return $this->precise_valid_content_net_sum;
    }

    public function setPreciseValidContentNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_valid_content_net_sum = $var;
    }

    public function getPersonId()
    {
        return $this->person_id;
    }

    public function setPersonId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_id = $var;
    }

    public function getPaymentTypeDescription()
    {
        return $this->payment_type_description;
    }

    public function setPaymentTypeDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->payment_type_description = $var;
    }

    public function getValidContentBruttoSum()
    {
        return $this->valid_content_brutto_sum;
    }

    public function setValidContentBruttoSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->valid_content_brutto_sum = $var;
    }

    public function getPreciseNetSum()
    {
        return $this->precise_net_sum;
    }

    public function setPreciseNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_net_sum = $var;
    }

    public function getPositionCount()
    {
        return $this->position_count;
    }

    public function setPositionCount(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->position_count = $var;
    }

    public function getOrderStateId()
    {
        return $this->order_state_id;
    }

    public function setOrderStateId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->order_state_id = $var;
    }

    public function getShippingTypeId()
    {
        return $this->shipping_type_id;
    }

    public function setShippingTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->shipping_type_id = $var;
    }

    public function getPersonTypeId()
    {
        return $this->person_type_id;
    }

    public function setPersonTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_type_id = $var;
    }

    public function getPreciseComputedGrossSum()
    {
        return $this->precise_computed_gross_sum;
    }

    public function setPreciseComputedGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_computed_gross_sum = $var;
    }

    public function getHasValidContents()
    {
        return $this->has_valid_contents;
    }

    public function setHasValidContents(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->has_valid_contents = $var;
    }

    public function getNetPaymentCost()
    {
        return $this->net_payment_cost;
    }

    public function setNetPaymentCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->net_payment_cost = $var;
    }

    public function getDeliveryPersonId()
    {
        return $this->delivery_person_id;
    }

    public function setDeliveryPersonId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->delivery_person_id = $var;
    }

    public function getShippingTypeDescription()
    {
        return $this->shipping_type_description;
    }

    public function setShippingTypeDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->shipping_type_description = $var;
    }

    public function getGrossSum()
    {
        return $this->gross_sum;
    }

    public function setGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->gross_sum = $var;
    }

    public function getUnitSymbol()
    {
        return $this->unit_symbol;
    }

    public function setUnitSymbol(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->unit_symbol = $var;
    }

    public function getPreciseNetPaymentCost()
    {
        return $this->precise_net_payment_cost;
    }

    public function setPreciseNetPaymentCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_net_payment_cost = $var;
    }

    public function getCustomerCharacteristicValue2()
    {
        return $this->customer_characteristic_value2;
    }

    public function setCustomerCharacteristicValue2(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->customer_characteristic_value2 = $var;
    }

    public function getPublicDescription()
    {
        return $this->public_description;
    }

    public function setPublicDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->public_description = $var;
    }

    public function getCurrencyId()
    {
        return $this->currency_id;
    }

    public function setCurrencyId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->currency_id = $var;
    }

    public function getCustomerCharacteristicValue1()
    {
        return $this->customer_characteristic_value1;
    }

    public function setCustomerCharacteristicValue1(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->customer_characteristic_value1 = $var;
    }

    public function getPreciseGrossSum()
    {
        return $this->precise_gross_sum;
    }

    public function setPreciseGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_gross_sum = $var;
    }

    public function getComputedGrossSum()
    {
        return $this->computed_gross_sum;
    }

    public function setComputedGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->computed_gross_sum = $var;
    }

    public function getValidContentNettoSum()
    {
        return $this->valid_content_netto_sum;
    }

    public function setValidContentNettoSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->valid_content_netto_sum = $var;
    }

    public function getShippingCost()
    {
        return $this->shipping_cost;
    }

    public function setShippingCost(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->shipping_cost = $var;
    }

    public function getCharacVal1RestrByPattern()
    {
        return $this->charac_val1_restr_by_pattern;
    }

    public function setCharacVal1RestrByPattern(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->charac_val1_restr_by_pattern = $var;
    }

    public function getPaymentTypeId()
    {
        return $this->payment_type_id;
    }

    public function setPaymentTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->payment_type_id = $var;
    }

    public function getPreciseValidContentGrossSum()
    {
        return $this->precise_valid_content_gross_sum;
    }

    public function setPreciseValidContentGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_valid_content_gross_sum = $var;
    }

    public function getPreciseComputedNetSum()
    {
        return $this->precise_computed_net_sum;
    }

    public function setPreciseComputedNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->precise_computed_net_sum = $var;
    }

    public function getOrderState()
    {
        return $this->order_state;
    }

    public function setOrderState(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->order_state = $var;
    }

    public function getComputedNetSum()
    {
        return $this->computed_net_sum;
    }

    public function setComputedNetSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->computed_net_sum = $var;
    }

    public function getValidContentGrossSum()
    {
        return $this->valid_content_gross_sum;
    }

    public function setValidContentGrossSum(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\decimalValue::class);
        $this->valid_content_gross_sum = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aa72f0a396473746f72652f656e67696e652f70726f636564757265732f" .
    "6f6d5f4765744f72646572735f436f6e646974696f6e735f41642e70726f" .
    "746f12286473746f72652e656e67696e652e6f6d5f4765744f7264657273" .
    "5f436f6e646974696f6e735f41641a136473746f72652f76616c7565732e" .
    "70726f746f1a1b6473746f72652f656e67696e652f6d6573736167652e70" .
    "726f746f1a236473746f72652f656e67696e652f6d657461696e666f726d" .
    "6174696f6e2e70726f746f22eb160a0a506172616d657465727312340a0f" .
    "6f726465725f62795f636f6c756d6e18012001280b321b2e6473746f7265" .
    "2e76616c7565732e696e746567657256616c7565121d0a146f726465725f" .
    "62795f636f6c756d6e5f6e756c6c18e90720012808123d0a186372656174" .
    "655f76616c69645f6f726465725f696e666f7318022001280b321b2e6473" .
    "746f72652e76616c7565732e626f6f6c65616e56616c756512260a1d6372" .
    "656174655f76616c69645f6f726465725f696e666f735f6e756c6c18ea07" .
    "20012808122e0a0a62727574746f5f73756d18032001280b321a2e647374" .
    "6f72652e76616c7565732e737472696e6756616c756512180a0f62727574" .
    "746f5f73756d5f6e756c6c18eb072001280812300a0b63757272656e6379" .
    "5f696418042001280b321b2e6473746f72652e76616c7565732e696e7465" .
    "67657256616c756512190a1063757272656e63795f69645f6e756c6c18ec" .
    "072001280812420a1e7175616e746974795f666f725f6f6e655f6f726465" .
    "725f636f6e74656e7418052001280b321a2e6473746f72652e76616c7565" .
    "732e737472696e6756616c7565122c0a237175616e746974795f666f725f" .
    "6f6e655f6f726465725f636f6e74656e745f6e756c6c18ed072001280812" .
    "2f0a0b636f6d62696e6174696f6e18062001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756512190a10636f6d62696e6174" .
    "696f6e5f6e756c6c18ee072001280812300a0966726f6d5f646174651807" .
    "2001280b321d2e6473746f72652e76616c7565732e74696d657374616d70" .
    "56616c756512170a0e66726f6d5f646174655f6e756c6c18ef0720012808" .
    "122e0a07746f5f6461746518082001280b321d2e6473746f72652e76616c" .
    "7565732e74696d657374616d7056616c756512150a0c746f5f646174655f" .
    "6e756c6c18f00720012808122f0a0a6f726465725f646573631809200128" .
    "0b321b2e6473746f72652e76616c7565732e626f6f6c65616e56616c7565" .
    "12180a0f6f726465725f646573635f6e756c6c18f1072001280812390a14" .
    "646174655f616e645f74696d655f666f726d6174180a2001280b321b2e64" .
    "73746f72652e76616c7565732e696e746567657256616c756512220a1964" .
    "6174655f616e645f74696d655f666f726d61745f6e756c6c18f207200128" .
    "0812310a0c696e636c7564655f74696d65180b2001280b321b2e6473746f" .
    "72652e76616c7565732e626f6f6c65616e56616c7565121a0a11696e636c" .
    "7564655f74696d655f6e756c6c18f3072001280812450a206765745f696e" .
    "666f5f666f725f76616c69645f6f726465725f636f6e74656e74180c2001" .
    "280b321b2e6473746f72652e76616c7565732e626f6f6c65616e56616c75" .
    "65122e0a256765745f696e666f5f666f725f76616c69645f6f726465725f" .
    "636f6e74656e745f6e756c6c18f4072001280812340a106f726465725f73" .
    "746174655f6c697374180d2001280b321a2e6473746f72652e76616c7565" .
    "732e737472696e6756616c7565121e0a156f726465725f73746174655f6c" .
    "6973745f6e756c6c18f5072001280812450a20736b69705f6f5f68617669" .
    "6e675f646966666572656e745f6f5f737461746573180e2001280b321b2e" .
    "6473746f72652e76616c7565732e626f6f6c65616e56616c7565122e0a25" .
    "736b69705f6f5f686176696e675f646966666572656e745f6f5f73746174" .
    "65735f6e756c6c18f6072001280812380a147061796d656e745f74797065" .
    "5f69645f6c697374180f2001280b321a2e6473746f72652e76616c756573" .
    "2e737472696e6756616c756512220a197061796d656e745f747970655f69" .
    "645f6c6973745f6e756c6c18f7072001280812390a157368697070696e67" .
    "5f747970655f69645f6c69737418102001280b321a2e6473746f72652e76" .
    "616c7565732e737472696e6756616c756512230a1a7368697070696e675f" .
    "747970655f69645f6c6973745f6e756c6c18f8072001280812400a1b7368" .
    "6f775f706572736f6e5f6368617261637465726973746963731811200128" .
    "0b321b2e6473746f72652e76616c7565732e626f6f6c65616e56616c7565" .
    "12290a2073686f775f706572736f6e5f6368617261637465726973746963" .
    "735f6e756c6c18f9072001280812420a1d636f6e766572745f726573756c" .
    "745f746f5f63757272656e63795f696418122001280b321b2e6473746f72" .
    "652e76616c7565732e696e746567657256616c7565122b0a22636f6e7665" .
    "72745f726573756c745f746f5f63757272656e63795f69645f6e756c6c18" .
    "fa072001280812450a20636f6e766572745f726573756c745f746f5f6769" .
    "76656e5f63757272656e637918132001280b321b2e6473746f72652e7661" .
    "6c7565732e626f6f6c65616e56616c7565122e0a25636f6e766572745f72" .
    "6573756c745f746f5f676976656e5f63757272656e63795f6e756c6c18fb" .
    "072001280812330a0e70757263686173655f6f7264657218142001280b32" .
    "1b2e6473746f72652e76616c7565732e626f6f6c65616e56616c7565121c" .
    "0a1370757263686173655f6f726465725f6e756c6c18fc07200128081242" .
    "0a1d696e7075745f6e6573745f6c6576656c5f6f5f696e666f5f636f6e64" .
    "7318152001280b321b2e6473746f72652e76616c7565732e696e74656765" .
    "7256616c7565122b0a22696e7075745f6e6573745f6c6576656c5f6f5f69" .
    "6e666f5f636f6e64735f6e756c6c18fd072001280812400a1c76616c7565" .
    "5f736570617261746f725f695f6e5f6f70657261746f7218162001280b32" .
    "1a2e6473746f72652e76616c7565732e737472696e6756616c7565122a0a" .
    "2176616c75655f736570617261746f725f695f6e5f6f70657261746f725f" .
    "6e756c6c18fe0720012808122b0a07636f756e74727918172001280b321a" .
    "2e6473746f72652e76616c7565732e737472696e6756616c756512150a0c" .
    "636f756e7472795f6e756c6c18ff072001280812300a0b6c616e67756167" .
    "655f696418182001280b321b2e6473746f72652e76616c7565732e696e74" .
    "6567657256616c756512190a106c616e67756167655f69645f6e756c6c18" .
    "80082001280812460a21696e7075745f6e6573745f6c6576656c5f6f5f63" .
    "6f6e5f696e666f5f636f6e647318192001280b321b2e6473746f72652e76" .
    "616c7565732e696e746567657256616c7565122f0a26696e7075745f6e65" .
    "73745f6c6576656c5f6f5f636f6e5f696e666f5f636f6e64735f6e756c6c" .
    "1881082001280812490a24636f6e64735f6d7573745f62655f66756c6669" .
    "6c6c65645f666f725f6f5f636f6e5f6964181a2001280b321b2e6473746f" .
    "72652e76616c7565732e626f6f6c65616e56616c756512320a29636f6e64" .
    "735f6d7573745f62655f66756c66696c6c65645f666f725f6f5f636f6e5f" .
    "69645f6e756c6c1882082001280812410a1c66696c7465725f62795f6e6f" .
    "64655f6964735f696e5f6f6e655f6964181b2001280b321b2e6473746f72" .
    "652e76616c7565732e696e746567657256616c7565122a0a2166696c7465" .
    "725f62795f6e6f64655f6964735f696e5f6f6e655f69645f6e756c6c1883" .
    "082001280812350a106765745f636f6d70757465645f73756d181c200128" .
    "0b321b2e6473746f72652e76616c7565732e626f6f6c65616e56616c7565" .
    "121e0a156765745f636f6d70757465645f73756d5f6e756c6c1884082001" .
    "280812440a1f6f6e6c795f76616c69645f706f735f666f725f636f6d7075" .
    "7465645f73756d181d2001280b321b2e6473746f72652e76616c7565732e" .
    "626f6f6c65616e56616c7565122d0a246f6e6c795f76616c69645f706f73" .
    "5f666f725f636f6d70757465645f73756d5f6e756c6c1885082001280812" .
    "440a206f726465725f73757263685f6964735f666f725f636f6d70757465" .
    "645f73756d181e2001280b321a2e6473746f72652e76616c7565732e7374" .
    "72696e6756616c7565122e0a256f726465725f73757263685f6964735f66" .
    "6f725f636f6d70757465645f73756d5f6e756c6c18860820012808229516" .
    "0a08526573706f6e736512480a106d6574615f696e666f726d6174696f6e" .
    "18022003280b322e2e6473746f72652e656e67696e652e6d657461696e66" .
    "6f726d6174696f6e2e4d657461496e666f726d6174696f6e122f0a076d65" .
    "737361676518032003280b321e2e6473746f72652e656e67696e652e6d65" .
    "73736167652e4d65737361676512430a03726f7718042003280b32362e64" .
    "73746f72652e656e67696e652e6f6d5f4765744f72646572735f436f6e64" .
    "6974696f6e735f41642e526573706f6e73652e526f771ac8140a03526f77" .
    "120f0a06726f775f696418904e2001280512380a136f726465725f646174" .
    "655f616e645f74696d6518914e2001280b321a2e6473746f72652e76616c" .
    "7565732e737472696e6756616c756512320a0c7061796d656e745f636f73" .
    "7418924e2001280b321b2e6473746f72652e76616c7565732e646563696d" .
    "616c56616c7565123b0a1664656c69766572795f646174655f616e645f74" .
    "696d6518934e2001280b321a2e6473746f72652e76616c7565732e737472" .
    "696e6756616c756512370a116e65745f7368697070696e675f636f737418" .
    "944e2001280b321b2e6473746f72652e76616c7565732e646563696d616c" .
    "56616c7565122d0a086f726465725f6e6f18954e2001280b321a2e647374" .
    "6f72652e76616c7565732e737472696e6756616c7565122f0a096e657474" .
    "6f5f73756d18964e2001280b321b2e6473746f72652e76616c7565732e64" .
    "6563696d616c56616c7565123c0a166c6173745f6564697465645f62795f" .
    "757365725f696418974e2001280b321b2e6473746f72652e76616c756573" .
    "2e696e746567657256616c7565122e0a086f726465725f696418984e2001" .
    "280b321b2e6473746f72652e76616c7565732e696e746567657256616c75" .
    "6512300a0a62727574746f5f73756d18994e2001280b321b2e6473746f72" .
    "652e76616c7565732e646563696d616c56616c7565123f0a197072656369" .
    "73655f6e65745f7368697070696e675f636f7374189a4e2001280b321b2e" .
    "6473746f72652e76616c7565732e646563696d616c56616c756512410a1c" .
    "6368617261635f76616c325f72657374725f62795f7061747465726e189b" .
    "4e2001280b321a2e6473746f72652e76616c7565732e737472696e675661" .
    "6c7565122d0a076e65745f73756d189c4e2001280b321b2e6473746f7265" .
    "2e76616c7565732e646563696d616c56616c7565123b0a1576616c69645f" .
    "636f6e74656e745f6e65745f73756d189d4e2001280b321b2e6473746f72" .
    "652e76616c7565732e646563696d616c56616c756512430a1d7072656369" .
    "73655f76616c69645f636f6e74656e745f6e65745f73756d189e4e200128" .
    "0b321b2e6473746f72652e76616c7565732e646563696d616c56616c7565" .
    "122f0a09706572736f6e5f6964189f4e2001280b321b2e6473746f72652e" .
    "76616c7565732e696e746567657256616c7565123d0a187061796d656e74" .
    "5f747970655f6465736372697074696f6e18a04e2001280b321a2e647374" .
    "6f72652e76616c7565732e737472696e6756616c7565123e0a1876616c69" .
    "645f636f6e74656e745f62727574746f5f73756d18a14e2001280b321b2e" .
    "6473746f72652e76616c7565732e646563696d616c56616c756512350a0f" .
    "707265636973655f6e65745f73756d18a24e2001280b321b2e6473746f72" .
    "652e76616c7565732e646563696d616c56616c756512340a0e706f736974" .
    "696f6e5f636f756e7418a34e2001280b321b2e6473746f72652e76616c75" .
    "65732e696e746567657256616c756512340a0e6f726465725f7374617465" .
    "5f696418a44e2001280b321b2e6473746f72652e76616c7565732e696e74" .
    "6567657256616c756512360a107368697070696e675f747970655f696418" .
    "a54e2001280b321b2e6473746f72652e76616c7565732e696e7465676572" .
    "56616c756512340a0e706572736f6e5f747970655f696418a64e2001280b" .
    "321b2e6473746f72652e76616c7565732e696e746567657256616c756512" .
    "400a1a707265636973655f636f6d70757465645f67726f73735f73756d18" .
    "a74e2001280b321b2e6473746f72652e76616c7565732e646563696d616c" .
    "56616c756512380a126861735f76616c69645f636f6e74656e747318a84e" .
    "2001280b321b2e6473746f72652e76616c7565732e626f6f6c65616e5661" .
    "6c756512360a106e65745f7061796d656e745f636f737418a94e2001280b" .
    "321b2e6473746f72652e76616c7565732e646563696d616c56616c756512" .
    "380a1264656c69766572795f706572736f6e5f696418aa4e2001280b321b" .
    "2e6473746f72652e76616c7565732e696e746567657256616c7565123e0a" .
    "197368697070696e675f747970655f6465736372697074696f6e18ab4e20" .
    "01280b321a2e6473746f72652e76616c7565732e737472696e6756616c75" .
    "65122f0a0967726f73735f73756d18ac4e2001280b321b2e6473746f7265" .
    "2e76616c7565732e646563696d616c56616c756512300a0b756e69745f73" .
    "796d626f6c18ad4e2001280b321a2e6473746f72652e76616c7565732e73" .
    "7472696e6756616c7565123e0a18707265636973655f6e65745f7061796d" .
    "656e745f636f737418ae4e2001280b321b2e6473746f72652e76616c7565" .
    "732e646563696d616c56616c756512430a1e637573746f6d65725f636861" .
    "72616374657269737469635f76616c75653218af4e2001280b321a2e6473" .
    "746f72652e76616c7565732e737472696e6756616c756512370a12707562" .
    "6c69635f6465736372697074696f6e18b04e2001280b321a2e6473746f72" .
    "652e76616c7565732e737472696e6756616c756512310a0b63757272656e" .
    "63795f696418b14e2001280b321b2e6473746f72652e76616c7565732e69" .
    "6e746567657256616c756512430a1e637573746f6d65725f636861726163" .
    "74657269737469635f76616c75653118b24e2001280b321a2e6473746f72" .
    "652e76616c7565732e737472696e6756616c756512370a11707265636973" .
    "655f67726f73735f73756d18b34e2001280b321b2e6473746f72652e7661" .
    "6c7565732e646563696d616c56616c756512380a12636f6d70757465645f" .
    "67726f73735f73756d18b44e2001280b321b2e6473746f72652e76616c75" .
    "65732e646563696d616c56616c7565123d0a1776616c69645f636f6e7465" .
    "6e745f6e6574746f5f73756d18b54e2001280b321b2e6473746f72652e76" .
    "616c7565732e646563696d616c56616c756512330a0d7368697070696e67" .
    "5f636f737418b64e2001280b321b2e6473746f72652e76616c7565732e64" .
    "6563696d616c56616c756512410a1c6368617261635f76616c315f726573" .
    "74725f62795f7061747465726e18b74e2001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756512350a0f7061796d656e745f" .
    "747970655f696418b84e2001280b321b2e6473746f72652e76616c756573" .
    "2e696e746567657256616c756512450a1f707265636973655f76616c6964" .
    "5f636f6e74656e745f67726f73735f73756d18b94e2001280b321b2e6473" .
    "746f72652e76616c7565732e646563696d616c56616c7565123e0a187072" .
    "65636973655f636f6d70757465645f6e65745f73756d18ba4e2001280b32" .
    "1b2e6473746f72652e76616c7565732e646563696d616c56616c75651230" .
    "0a0b6f726465725f737461746518bb4e2001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756512360a10636f6d7075746564" .
    "5f6e65745f73756d18bc4e2001280b321b2e6473746f72652e76616c7565" .
    "732e646563696d616c56616c7565123d0a1776616c69645f636f6e74656e" .
    "745f67726f73735f73756d18bd4e2001280b321b2e6473746f72652e7661" .
    "6c7565732e646563696d616c56616c7565425b0a1b696f2e6473746f7265" .
    "2e656e67696e652e70726f636564757265735a3c676f73646b2e6473746f" .
    "72652e64652f656e67696e652f70726f636564757265732f6f6d5f476574" .
    "4f72646572735f436f6e646974696f6e735f4164620670726f746f33"
));

