<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/pm_GetPersonProperties_Pu.proto

namespace Dstore\Engine\Pm_GetPersonProperties_Pu;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $sorted_result = null;
    private $sorted_result_null = false;
    private $include_person_charac_category_id = null;
    private $include_person_charac_category_id_null = false;
    private $input_parameter = null;
    private $input_parameter_null = false;
    private $input_is_unique_id = null;
    private $input_is_unique_id_null = false;
    private $person_type_id = null;
    private $person_type_id_null = false;
    private $language_id = null;
    private $language_id_null = false;
    private $characteristic_id_list = null;
    private $characteristic_id_list_null = false;
    private $date_format = null;
    private $date_format_null = false;
    private $case_sensitive = null;
    private $case_sensitive_null = false;
    private $person_id = null;
    private $person_id_null = false;
    private $date_and_time = null;
    private $date_and_time_null = false;
    private $get_actual_properties = null;
    private $get_actual_properties_null = false;
    private $separator_for_ident_vals = null;
    private $separator_for_ident_vals_null = false;

    public function getSortedResult()
    {
        return $this->sorted_result;
    }

    public function setSortedResult(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->sorted_result = $var;
    }

    public function getSortedResultNull()
    {
        return $this->sorted_result_null;
    }

    public function setSortedResultNull($var)
    {
        GPBUtil::checkBool($var);
        $this->sorted_result_null = $var;
    }

    public function getIncludePersonCharacCategoryId()
    {
        return $this->include_person_charac_category_id;
    }

    public function setIncludePersonCharacCategoryId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->include_person_charac_category_id = $var;
    }

    public function getIncludePersonCharacCategoryIdNull()
    {
        return $this->include_person_charac_category_id_null;
    }

    public function setIncludePersonCharacCategoryIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_person_charac_category_id_null = $var;
    }

    public function getInputParameter()
    {
        return $this->input_parameter;
    }

    public function setInputParameter(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->input_parameter = $var;
    }

    public function getInputParameterNull()
    {
        return $this->input_parameter_null;
    }

    public function setInputParameterNull($var)
    {
        GPBUtil::checkBool($var);
        $this->input_parameter_null = $var;
    }

    public function getInputIsUniqueId()
    {
        return $this->input_is_unique_id;
    }

    public function setInputIsUniqueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->input_is_unique_id = $var;
    }

    public function getInputIsUniqueIdNull()
    {
        return $this->input_is_unique_id_null;
    }

    public function setInputIsUniqueIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->input_is_unique_id_null = $var;
    }

    public function getPersonTypeId()
    {
        return $this->person_type_id;
    }

    public function setPersonTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_type_id = $var;
    }

    public function getPersonTypeIdNull()
    {
        return $this->person_type_id_null;
    }

    public function setPersonTypeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_type_id_null = $var;
    }

    public function getLanguageId()
    {
        return $this->language_id;
    }

    public function setLanguageId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->language_id = $var;
    }

    public function getLanguageIdNull()
    {
        return $this->language_id_null;
    }

    public function setLanguageIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->language_id_null = $var;
    }

    public function getCharacteristicIdList()
    {
        return $this->characteristic_id_list;
    }

    public function setCharacteristicIdList(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->characteristic_id_list = $var;
    }

    public function getCharacteristicIdListNull()
    {
        return $this->characteristic_id_list_null;
    }

    public function setCharacteristicIdListNull($var)
    {
        GPBUtil::checkBool($var);
        $this->characteristic_id_list_null = $var;
    }

    public function getDateFormat()
    {
        return $this->date_format;
    }

    public function setDateFormat(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->date_format = $var;
    }

    public function getDateFormatNull()
    {
        return $this->date_format_null;
    }

    public function setDateFormatNull($var)
    {
        GPBUtil::checkBool($var);
        $this->date_format_null = $var;
    }

    public function getCaseSensitive()
    {
        return $this->case_sensitive;
    }

    public function setCaseSensitive(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->case_sensitive = $var;
    }

    public function getCaseSensitiveNull()
    {
        return $this->case_sensitive_null;
    }

    public function setCaseSensitiveNull($var)
    {
        GPBUtil::checkBool($var);
        $this->case_sensitive_null = $var;
    }

    public function getPersonId()
    {
        return $this->person_id;
    }

    public function setPersonId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_id = $var;
    }

    public function getPersonIdNull()
    {
        return $this->person_id_null;
    }

    public function setPersonIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_id_null = $var;
    }

    public function getDateAndTime()
    {
        return $this->date_and_time;
    }

    public function setDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->date_and_time = $var;
    }

    public function getDateAndTimeNull()
    {
        return $this->date_and_time_null;
    }

    public function setDateAndTimeNull($var)
    {
        GPBUtil::checkBool($var);
        $this->date_and_time_null = $var;
    }

    public function getGetActualProperties()
    {
        return $this->get_actual_properties;
    }

    public function setGetActualProperties(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->get_actual_properties = $var;
    }

    public function getGetActualPropertiesNull()
    {
        return $this->get_actual_properties_null;
    }

    public function setGetActualPropertiesNull($var)
    {
        GPBUtil::checkBool($var);
        $this->get_actual_properties_null = $var;
    }

    public function getSeparatorForIdentVals()
    {
        return $this->separator_for_ident_vals;
    }

    public function setSeparatorForIdentVals(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->separator_for_ident_vals = $var;
    }

    public function getSeparatorForIdentValsNull()
    {
        return $this->separator_for_ident_vals_null;
    }

    public function setSeparatorForIdentValsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->separator_for_ident_vals_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Pm_GetPersonProperties_Pu\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $value_restricted_by_pattern = null;
    private $characteristic_description = null;
    private $field_type_id = null;
    private $characteristic_id = null;
    private $value_id = null;
    private $modify = null;
    private $max_length = null;
    private $predefined_values = null;
    private $person_charac_category_id = null;
    private $read_access_restriction_pattern = null;
    private $person_id = null;
    private $required = null;
    private $actual_value = null;
    private $value = null;
    private $visible = null;
    private $last_edited = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getValueRestrictedByPattern()
    {
        return $this->value_restricted_by_pattern;
    }

    public function setValueRestrictedByPattern(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->value_restricted_by_pattern = $var;
    }

    public function getCharacteristicDescription()
    {
        return $this->characteristic_description;
    }

    public function setCharacteristicDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->characteristic_description = $var;
    }

    public function getFieldTypeId()
    {
        return $this->field_type_id;
    }

    public function setFieldTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->field_type_id = $var;
    }

    public function getCharacteristicId()
    {
        return $this->characteristic_id;
    }

    public function setCharacteristicId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->characteristic_id = $var;
    }

    public function getValueId()
    {
        return $this->value_id;
    }

    public function setValueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->value_id = $var;
    }

    public function getModify()
    {
        return $this->modify;
    }

    public function setModify(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->modify = $var;
    }

    public function getMaxLength()
    {
        return $this->max_length;
    }

    public function setMaxLength(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->max_length = $var;
    }

    public function getPredefinedValues()
    {
        return $this->predefined_values;
    }

    public function setPredefinedValues(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->predefined_values = $var;
    }

    public function getPersonCharacCategoryId()
    {
        return $this->person_charac_category_id;
    }

    public function setPersonCharacCategoryId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_charac_category_id = $var;
    }

    public function getReadAccessRestrictionPattern()
    {
        return $this->read_access_restriction_pattern;
    }

    public function setReadAccessRestrictionPattern(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->read_access_restriction_pattern = $var;
    }

    public function getPersonId()
    {
        return $this->person_id;
    }

    public function setPersonId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_id = $var;
    }

    public function getRequired()
    {
        return $this->required;
    }

    public function setRequired(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->required = $var;
    }

    public function getActualValue()
    {
        return $this->actual_value;
    }

    public function setActualValue(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->actual_value = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->value = $var;
    }

    public function getVisible()
    {
        return $this->visible;
    }

    public function setVisible(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->visible = $var;
    }

    public function getLastEdited()
    {
        return $this->last_edited;
    }

    public function setLastEdited(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->last_edited = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af4130a386473746f72652f656e67696e652f70726f636564757265732f" .
    "706d5f476574506572736f6e50726f706572746965735f50752e70726f74" .
    "6f12276473746f72652e656e67696e652e706d5f476574506572736f6e50" .
    "726f706572746965735f50751a136473746f72652f76616c7565732e7072" .
    "6f746f1a1b6473746f72652f656e67696e652f6d6573736167652e70726f" .
    "746f1a236473746f72652f656e67696e652f6d657461696e666f726d6174" .
    "696f6e2e70726f746f2289090a0a506172616d657465727312320a0d736f" .
    "727465645f726573756c7418012001280b321b2e6473746f72652e76616c" .
    "7565732e626f6f6c65616e56616c7565121b0a12736f727465645f726573" .
    "756c745f6e756c6c18e9072001280812460a21696e636c7564655f706572" .
    "736f6e5f6368617261635f63617465676f72795f696418022001280b321b" .
    "2e6473746f72652e76616c7565732e626f6f6c65616e56616c7565122f0a" .
    "26696e636c7564655f706572736f6e5f6368617261635f63617465676f72" .
    "795f69645f6e756c6c18ea072001280812330a0f696e7075745f70617261" .
    "6d6574657218032001280b321a2e6473746f72652e76616c7565732e7374" .
    "72696e6756616c7565121d0a14696e7075745f706172616d657465725f6e" .
    "756c6c18eb072001280812370a12696e7075745f69735f756e697175655f" .
    "696418042001280b321b2e6473746f72652e76616c7565732e696e746567" .
    "657256616c756512200a17696e7075745f69735f756e697175655f69645f" .
    "6e756c6c18ec072001280812330a0e706572736f6e5f747970655f696418" .
    "052001280b321b2e6473746f72652e76616c7565732e696e746567657256" .
    "616c7565121c0a13706572736f6e5f747970655f69645f6e756c6c18ed07" .
    "2001280812300a0b6c616e67756167655f696418062001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c756512190a106c61" .
    "6e67756167655f69645f6e756c6c18ee0720012808123a0a166368617261" .
    "6374657269737469635f69645f6c69737418072001280b321a2e6473746f" .
    "72652e76616c7565732e737472696e6756616c756512240a1b6368617261" .
    "6374657269737469635f69645f6c6973745f6e756c6c18ef072001280812" .
    "2f0a0b646174655f666f726d617418082001280b321a2e6473746f72652e" .
    "76616c7565732e737472696e6756616c756512190a10646174655f666f72" .
    "6d61745f6e756c6c18f0072001280812330a0e636173655f73656e736974" .
    "69766518092001280b321b2e6473746f72652e76616c7565732e626f6f6c" .
    "65616e56616c7565121c0a13636173655f73656e7369746976655f6e756c" .
    "6c18f10720012808122e0a09706572736f6e5f6964180a2001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c756512170a0e" .
    "706572736f6e5f69645f6e756c6c18f2072001280812340a0d646174655f" .
    "616e645f74696d65180b2001280b321d2e6473746f72652e76616c756573" .
    "2e74696d657374616d7056616c7565121b0a12646174655f616e645f7469" .
    "6d655f6e756c6c18f30720012808123a0a156765745f61637475616c5f70" .
    "726f70657274696573180c2001280b321b2e6473746f72652e76616c7565" .
    "732e626f6f6c65616e56616c756512230a1a6765745f61637475616c5f70" .
    "726f706572746965735f6e756c6c18f40720012808123c0a187365706172" .
    "61746f725f666f725f6964656e745f76616c73180d2001280b321a2e6473" .
    "746f72652e76616c7565732e737472696e6756616c756512260a1d736570" .
    "617261746f725f666f725f6964656e745f76616c735f6e756c6c18f50720" .
    "01280822c7080a08526573706f6e736512480a106d6574615f696e666f72" .
    "6d6174696f6e18022003280b322e2e6473746f72652e656e67696e652e6d" .
    "657461696e666f726d6174696f6e2e4d657461496e666f726d6174696f6e" .
    "122f0a076d65737361676518032003280b321e2e6473746f72652e656e67" .
    "696e652e6d6573736167652e4d65737361676512420a03726f7718042003" .
    "280b32352e6473746f72652e656e67696e652e706d5f476574506572736f" .
    "6e50726f706572746965735f50752e526573706f6e73652e526f771afb06" .
    "0a03526f77120f0a06726f775f696418904e2001280512400a1b76616c75" .
    "655f726573747269637465645f62795f7061747465726e18914e2001280b" .
    "321a2e6473746f72652e76616c7565732e737472696e6756616c7565123f" .
    "0a1a63686172616374657269737469635f6465736372697074696f6e1892" .
    "4e2001280b321a2e6473746f72652e76616c7565732e737472696e675661" .
    "6c756512330a0d6669656c645f747970655f696418934e2001280b321b2e" .
    "6473746f72652e76616c7565732e696e746567657256616c756512370a11" .
    "63686172616374657269737469635f696418944e2001280b321b2e647374" .
    "6f72652e76616c7565732e696e746567657256616c7565122e0a0876616c" .
    "75655f696418954e2001280b321b2e6473746f72652e76616c7565732e69" .
    "6e746567657256616c7565122c0a066d6f6469667918964e2001280b321b" .
    "2e6473746f72652e76616c7565732e696e746567657256616c756512300a" .
    "0a6d61785f6c656e67746818974e2001280b321b2e6473746f72652e7661" .
    "6c7565732e696e746567657256616c756512370a11707265646566696e65" .
    "645f76616c75657318984e2001280b321b2e6473746f72652e76616c7565" .
    "732e626f6f6c65616e56616c7565123f0a19706572736f6e5f6368617261" .
    "635f63617465676f72795f696418994e2001280b321b2e6473746f72652e" .
    "76616c7565732e696e746567657256616c756512440a1f726561645f6163" .
    "636573735f7265737472696374696f6e5f7061747465726e189a4e200128" .
    "0b321a2e6473746f72652e76616c7565732e737472696e6756616c756512" .
    "2f0a09706572736f6e5f6964189b4e2001280b321b2e6473746f72652e76" .
    "616c7565732e696e746567657256616c7565122e0a087265717569726564" .
    "189c4e2001280b321b2e6473746f72652e76616c7565732e626f6f6c6561" .
    "6e56616c756512310a0c61637475616c5f76616c7565189d4e2001280b32" .
    "1a2e6473746f72652e76616c7565732e737472696e6756616c7565122a0a" .
    "0576616c7565189e4e2001280b321a2e6473746f72652e76616c7565732e" .
    "737472696e6756616c7565122d0a0776697369626c65189f4e2001280b32" .
    "1b2e6473746f72652e76616c7565732e626f6f6c65616e56616c75651233" .
    "0a0b6c6173745f65646974656418a04e2001280b321d2e6473746f72652e" .
    "76616c7565732e74696d657374616d7056616c7565425a0a1b696f2e6473" .
    "746f72652e656e67696e652e70726f636564757265735a3b676f73646b2e" .
    "6473746f72652e64652f656e67696e652f70726f636564757265732f706d" .
    "5f476574506572736f6e50726f706572746965735f5075620670726f746f" .
    "33"
));

