<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/pm_GetGroups_Ad.proto

namespace Dstore\Engine\Pm_GetGroups_Ad;

require_once('dstore/values.pb.php');
require_once('dstore/engine/message.pb.php');
require_once('dstore/engine/metainformation.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $person_id = null;
    private $person_id_null = false;
    private $person_type_id = null;
    private $person_type_id_null = false;
    private $include_independent_groups = null;
    private $include_independent_groups_null = false;

    public function getPersonId()
    {
        return $this->person_id;
    }

    public function setPersonId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_id = $var;
    }

    public function getPersonIdNull()
    {
        return $this->person_id_null;
    }

    public function setPersonIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_id_null = $var;
    }

    public function getPersonTypeId()
    {
        return $this->person_type_id;
    }

    public function setPersonTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_type_id = $var;
    }

    public function getPersonTypeIdNull()
    {
        return $this->person_type_id_null;
    }

    public function setPersonTypeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_type_id_null = $var;
    }

    public function getIncludeIndependentGroups()
    {
        return $this->include_independent_groups;
    }

    public function setIncludeIndependentGroups(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\booleanValue::class);
        $this->include_independent_groups = $var;
    }

    public function getIncludeIndependentGroupsNull()
    {
        return $this->include_independent_groups_null;
    }

    public function setIncludeIndependentGroupsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->include_independent_groups_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Pm_GetGroups_Ad\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $group_description = null;
    private $condition_id = null;
    private $sort_no = null;
    private $person_type_id = null;
    private $group_id = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getGroupDescription()
    {
        return $this->group_description;
    }

    public function setGroupDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->group_description = $var;
    }

    public function getConditionId()
    {
        return $this->condition_id;
    }

    public function setConditionId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->condition_id = $var;
    }

    public function getSortNo()
    {
        return $this->sort_no;
    }

    public function setSortNo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->sort_no = $var;
    }

    public function getPersonTypeId()
    {
        return $this->person_type_id;
    }

    public function setPersonTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_type_id = $var;
    }

    public function getGroupId()
    {
        return $this->group_id;
    }

    public function setGroupId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->group_id = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af2070a2e6473746f72652f656e67696e652f70726f636564757265732f" .
    "706d5f47657447726f7570735f41642e70726f746f121d6473746f72652e" .
    "656e67696e652e706d5f47657447726f7570735f41641a136473746f7265" .
    "2f76616c7565732e70726f746f1a1b6473746f72652f656e67696e652f6d" .
    "6573736167652e70726f746f1a236473746f72652f656e67696e652f6d65" .
    "7461696e666f726d6174696f6e2e70726f746f2293020a0a506172616d65" .
    "74657273122e0a09706572736f6e5f696418012001280b321b2e6473746f" .
    "72652e76616c7565732e696e746567657256616c756512170a0e70657273" .
    "6f6e5f69645f6e756c6c18e9072001280812330a0e706572736f6e5f7479" .
    "70655f696418022001280b321b2e6473746f72652e76616c7565732e696e" .
    "746567657256616c7565121c0a13706572736f6e5f747970655f69645f6e" .
    "756c6c18ea0720012808123f0a1a696e636c7564655f696e646570656e64" .
    "656e745f67726f75707318032001280b321b2e6473746f72652e76616c75" .
    "65732e626f6f6c65616e56616c756512280a1f696e636c7564655f696e64" .
    "6570656e64656e745f67726f7570735f6e756c6c18eb072001280822d903" .
    "0a08526573706f6e736512480a106d6574615f696e666f726d6174696f6e" .
    "18022003280b322e2e6473746f72652e656e67696e652e6d657461696e66" .
    "6f726d6174696f6e2e4d657461496e666f726d6174696f6e122f0a076d65" .
    "737361676518032003280b321e2e6473746f72652e656e67696e652e6d65" .
    "73736167652e4d65737361676512380a03726f7718042003280b322b2e64" .
    "73746f72652e656e67696e652e706d5f47657447726f7570735f41642e52" .
    "6573706f6e73652e526f771a97020a03526f77120f0a06726f775f696418" .
    "904e2001280512360a1167726f75705f6465736372697074696f6e18914e" .
    "2001280b321a2e6473746f72652e76616c7565732e737472696e6756616c" .
    "756512320a0c636f6e646974696f6e5f696418924e2001280b321b2e6473" .
    "746f72652e76616c7565732e696e746567657256616c7565122d0a07736f" .
    "72745f6e6f18934e2001280b321b2e6473746f72652e76616c7565732e69" .
    "6e746567657256616c756512340a0e706572736f6e5f747970655f696418" .
    "944e2001280b321b2e6473746f72652e76616c7565732e696e7465676572" .
    "56616c7565122e0a0867726f75705f696418954e2001280b321b2e647374" .
    "6f72652e76616c7565732e696e746567657256616c756542500a1b696f2e" .
    "6473746f72652e656e67696e652e70726f636564757265735a31676f7364" .
    "6b2e6473746f72652e64652f656e67696e652f70726f636564757265732f" .
    "706d5f47657447726f7570735f4164620670726f746f33"
));

