<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/pm_GetPeriodsForPredefVals_Ad.proto

namespace Dstore\Engine\Pm_GetPeriodsForPredefVals_Ad;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Parameters extends \Google\Protobuf\Internal\Message
{
    private $person_characteristic_id = null;
    private $person_characteristic_id_null = false;
    private $value_id = null;
    private $value_id_null = false;

    public function getPersonCharacteristicId()
    {
        return $this->person_characteristic_id;
    }

    public function setPersonCharacteristicId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_characteristic_id = $var;
    }

    public function getPersonCharacteristicIdNull()
    {
        return $this->person_characteristic_id_null;
    }

    public function setPersonCharacteristicIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->person_characteristic_id_null = $var;
    }

    public function getValueId()
    {
        return $this->value_id;
    }

    public function setValueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->value_id = $var;
    }

    public function getValueIdNull()
    {
        return $this->value_id_null;
    }

    public function setValueIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->value_id_null = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $meta_information;
    private $message;
    private $row;

    public function getMetaInformation()
    {
        return $this->meta_information;
    }

    public function setMetaInformation(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Metainformation\MetaInformation::class);
        $this->meta_information = $var;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Message\Message::class);
        $this->message = $var;
    }

    public function getRow()
    {
        return $this->row;
    }

    public function setRow(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Engine\Pm_GetPeriodsForPredefVals_Ad\Response_Row::class);
        $this->row = $var;
    }

}

class Response_Row extends \Google\Protobuf\Internal\Message
{
    private $row_id = 0;
    private $value_restricted_by_pattern = null;
    private $valid_to = null;
    private $person_characteristic_id = null;
    private $value = null;
    private $valid_to_char = null;
    private $valid_from = null;
    private $value_id = null;
    private $valid_from_char = null;

    public function getRowId()
    {
        return $this->row_id;
    }

    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    public function getValueRestrictedByPattern()
    {
        return $this->value_restricted_by_pattern;
    }

    public function setValueRestrictedByPattern(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->value_restricted_by_pattern = $var;
    }

    public function getValidTo()
    {
        return $this->valid_to;
    }

    public function setValidTo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->valid_to = $var;
    }

    public function getPersonCharacteristicId()
    {
        return $this->person_characteristic_id;
    }

    public function setPersonCharacteristicId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->person_characteristic_id = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->value = $var;
    }

    public function getValidToChar()
    {
        return $this->valid_to_char;
    }

    public function setValidToChar(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->valid_to_char = $var;
    }

    public function getValidFrom()
    {
        return $this->valid_from;
    }

    public function setValidFrom(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\timestampValue::class);
        $this->valid_from = $var;
    }

    public function getValueId()
    {
        return $this->value_id;
    }

    public function setValueId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\integerValue::class);
        $this->value_id = $var;
    }

    public function getValidFromChar()
    {
        return $this->valid_from_char;
    }

    public function setValidFromChar(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\stringValue::class);
        $this->valid_from_char = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0afe080a3c6473746f72652f656e67696e652f70726f636564757265732f" .
    "706d5f476574506572696f6473466f7250726564656656616c735f41642e" .
    "70726f746f122b6473746f72652e656e67696e652e706d5f476574506572" .
    "696f6473466f7250726564656656616c735f41641a136473746f72652f76" .
    "616c7565732e70726f746f1a1b6473746f72652f656e67696e652f6d6573" .
    "736167652e70726f746f1a236473746f72652f656e67696e652f6d657461" .
    "696e666f726d6174696f6e2e70726f746f22ba010a0a506172616d657465" .
    "7273123d0a18706572736f6e5f63686172616374657269737469635f6964" .
    "18012001280b321b2e6473746f72652e76616c7565732e696e7465676572" .
    "56616c756512260a1d706572736f6e5f6368617261637465726973746963" .
    "5f69645f6e756c6c18e90720012808122d0a0876616c75655f6964180220" .
    "01280b321b2e6473746f72652e76616c7565732e696e746567657256616c" .
    "756512160a0d76616c75655f69645f6e756c6c18ea07200128082294050a" .
    "08526573706f6e736512480a106d6574615f696e666f726d6174696f6e18" .
    "022003280b322e2e6473746f72652e656e67696e652e6d657461696e666f" .
    "726d6174696f6e2e4d657461496e666f726d6174696f6e122f0a076d6573" .
    "7361676518032003280b321e2e6473746f72652e656e67696e652e6d6573" .
    "736167652e4d65737361676512460a03726f7718042003280b32392e6473" .
    "746f72652e656e67696e652e706d5f476574506572696f6473466f725072" .
    "6564656656616c735f41642e526573706f6e73652e526f771ac4030a0352" .
    "6f77120f0a06726f775f696418904e2001280512400a1b76616c75655f72" .
    "6573747269637465645f62795f7061747465726e18914e2001280b321a2e" .
    "6473746f72652e76616c7565732e737472696e6756616c756512300a0876" .
    "616c69645f746f18924e2001280b321d2e6473746f72652e76616c756573" .
    "2e74696d657374616d7056616c7565123e0a18706572736f6e5f63686172" .
    "616374657269737469635f696418934e2001280b321b2e6473746f72652e" .
    "76616c7565732e696e746567657256616c7565122a0a0576616c75651894" .
    "4e2001280b321a2e6473746f72652e76616c7565732e737472696e675661" .
    "6c756512320a0d76616c69645f746f5f6368617218954e2001280b321a2e" .
    "6473746f72652e76616c7565732e737472696e6756616c756512320a0a76" .
    "616c69645f66726f6d18964e2001280b321d2e6473746f72652e76616c75" .
    "65732e74696d657374616d7056616c7565122e0a0876616c75655f696418" .
    "974e2001280b321b2e6473746f72652e76616c7565732e696e7465676572" .
    "56616c756512340a0f76616c69645f66726f6d5f6368617218984e200128" .
    "0b321a2e6473746f72652e76616c7565732e737472696e6756616c756542" .
    "5e0a1b696f2e6473746f72652e656e67696e652e70726f63656475726573" .
    "5a3f676f73646b2e6473746f72652e64652f656e67696e652f70726f6365" .
    "64757265732f706d5f476574506572696f6473466f725072656465665661" .
    "6c735f4164620670726f746f33"
));

