<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetLicenceKeyData.proto

namespace Dstore\Engine\Mi_GetLicenceKeyData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.mi_GetLicenceKeyData.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\MiGetLicenceKeyData::initOnce();
        parent::__construct();
    }

}

