<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/mi_GetLicenceKeyData.proto

namespace Dstore\Engine\Mi_GetLicenceKeyData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.mi_GetLicenceKeyData.Response.Row</code>
 */
class Response_Row extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 row_id = 10000;</code>
     */
    private $row_id = 0;
    /**
     * <pre>
     * Hinweise zum "LicenceParameter". Derzeit nur gefüllt, wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert zum "LicenceParameter" einsehen zu dürfen (hier steht dann, welche Rechte fehlen).
     * </pre>
     *
     * <code>.dstore.values.StringValue comment = 10001;</code>
     */
    private $comment = null;
    /**
     * <pre>
     * Falls die der ermittelten Kennzahl zugrunde liegenden Daten auf eine bestimmte Zeit-Periode eingeschränkt wurden, steht hier eine ensprechende Angabe der Art "last 30 days" oder "period 03/01/2009 - 03/31/2009" - sonst "NULL"
     * </pre>
     *
     * <code>.dstore.values.StringValue underlying_time_period = 10002;</code>
     */
    private $underlying_time_period = null;
    /**
     * <pre>
     * Der aktuelle Wert für die Kennzahl "LicenceParameter". Ist "NULL", wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert einsehen zu dürfen. In "Comment" steht dann, welche Rechte fehlen.
     * </pre>
     *
     * <code>.dstore.values.StringValue current_value = 10003;</code>
     */
    private $current_value = null;
    /**
     * <pre>
     * Eine "Kennzahl" wie z.B. "NumberOfPersons" oder "NumberOfOrders"
     * </pre>
     *
     * <code>.dstore.values.StringValue licence_parameter = 10004;</code>
     */
    private $licence_parameter = null;
    /**
     * <pre>
     * Der aktuelle Zeitpunkt (der Ausführung dieser Prozedur und damit der Ermittlung der Kennzahlen). Hinweis : Dient der leichteren Nachvollziehbarkeit falls die Kennzahlen irgendwo historisch aufgezeichnet werden sollen.
     * </pre>
     *
     * <code>.dstore.values.TimestampValue current_date_and_time = 10005;</code>
     */
    private $current_date_and_time = null;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\MiGetLicenceKeyData::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function getRowId()
    {
        return $this->row_id;
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    /**
     * <pre>
     * Hinweise zum "LicenceParameter". Derzeit nur gefüllt, wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert zum "LicenceParameter" einsehen zu dürfen (hier steht dann, welche Rechte fehlen).
     * </pre>
     *
     * <code>.dstore.values.StringValue comment = 10001;</code>
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * <pre>
     * Hinweise zum "LicenceParameter". Derzeit nur gefüllt, wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert zum "LicenceParameter" einsehen zu dürfen (hier steht dann, welche Rechte fehlen).
     * </pre>
     *
     * <code>.dstore.values.StringValue comment = 10001;</code>
     */
    public function setComment(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->comment = $var;
    }

    /**
     * <pre>
     * Falls die der ermittelten Kennzahl zugrunde liegenden Daten auf eine bestimmte Zeit-Periode eingeschränkt wurden, steht hier eine ensprechende Angabe der Art "last 30 days" oder "period 03/01/2009 - 03/31/2009" - sonst "NULL"
     * </pre>
     *
     * <code>.dstore.values.StringValue underlying_time_period = 10002;</code>
     */
    public function getUnderlyingTimePeriod()
    {
        return $this->underlying_time_period;
    }

    /**
     * <pre>
     * Falls die der ermittelten Kennzahl zugrunde liegenden Daten auf eine bestimmte Zeit-Periode eingeschränkt wurden, steht hier eine ensprechende Angabe der Art "last 30 days" oder "period 03/01/2009 - 03/31/2009" - sonst "NULL"
     * </pre>
     *
     * <code>.dstore.values.StringValue underlying_time_period = 10002;</code>
     */
    public function setUnderlyingTimePeriod(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->underlying_time_period = $var;
    }

    /**
     * <pre>
     * Der aktuelle Wert für die Kennzahl "LicenceParameter". Ist "NULL", wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert einsehen zu dürfen. In "Comment" steht dann, welche Rechte fehlen.
     * </pre>
     *
     * <code>.dstore.values.StringValue current_value = 10003;</code>
     */
    public function getCurrentValue()
    {
        return $this->current_value;
    }

    /**
     * <pre>
     * Der aktuelle Wert für die Kennzahl "LicenceParameter". Ist "NULL", wenn der Benutzer (der diese Prozedur aufruft) nicht über genügend Rechte verfügt, den Wert einsehen zu dürfen. In "Comment" steht dann, welche Rechte fehlen.
     * </pre>
     *
     * <code>.dstore.values.StringValue current_value = 10003;</code>
     */
    public function setCurrentValue(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->current_value = $var;
    }

    /**
     * <pre>
     * Eine "Kennzahl" wie z.B. "NumberOfPersons" oder "NumberOfOrders"
     * </pre>
     *
     * <code>.dstore.values.StringValue licence_parameter = 10004;</code>
     */
    public function getLicenceParameter()
    {
        return $this->licence_parameter;
    }

    /**
     * <pre>
     * Eine "Kennzahl" wie z.B. "NumberOfPersons" oder "NumberOfOrders"
     * </pre>
     *
     * <code>.dstore.values.StringValue licence_parameter = 10004;</code>
     */
    public function setLicenceParameter(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->licence_parameter = $var;
    }

    /**
     * <pre>
     * Der aktuelle Zeitpunkt (der Ausführung dieser Prozedur und damit der Ermittlung der Kennzahlen). Hinweis : Dient der leichteren Nachvollziehbarkeit falls die Kennzahlen irgendwo historisch aufgezeichnet werden sollen.
     * </pre>
     *
     * <code>.dstore.values.TimestampValue current_date_and_time = 10005;</code>
     */
    public function getCurrentDateAndTime()
    {
        return $this->current_date_and_time;
    }

    /**
     * <pre>
     * Der aktuelle Zeitpunkt (der Ausführung dieser Prozedur und damit der Ermittlung der Kennzahlen). Hinweis : Dient der leichteren Nachvollziehbarkeit falls die Kennzahlen irgendwo historisch aufgezeichnet werden sollen.
     * </pre>
     *
     * <code>.dstore.values.TimestampValue current_date_and_time = 10005;</code>
     */
    public function setCurrentDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\TimestampValue::class);
        $this->current_date_and_time = $var;
    }

}

