<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/im_CountBinariesForTreeNode.proto

namespace Dstore\Engine\Im_CountBinariesForTreeNode;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.im_CountBinariesForTreeNode.Response.Row</code>
 */
class Response_Row extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 row_id = 10000;</code>
     */
    private $row_id = 0;
    /**
     * <pre>
     * Anzahl der zugewiesenen Binärobjekte
     * </pre>
     *
     * <code>.dstore.values.IntegerValue number_of_binaries = 10001;</code>
     */
    private $number_of_binaries = null;
    /**
     * <pre>
     * Zur "&#64;TreeNodeID" zugehörige ID des Artikel-Elementes
     * </pre>
     *
     * <code>.dstore.values.IntegerValue node_id = 10002;</code>
     */
    private $node_id = null;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\ImCountBinariesForTreeNode::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function getRowId()
    {
        return $this->row_id;
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    /**
     * <pre>
     * Anzahl der zugewiesenen Binärobjekte
     * </pre>
     *
     * <code>.dstore.values.IntegerValue number_of_binaries = 10001;</code>
     */
    public function getNumberOfBinaries()
    {
        return $this->number_of_binaries;
    }

    /**
     * <pre>
     * Anzahl der zugewiesenen Binärobjekte
     * </pre>
     *
     * <code>.dstore.values.IntegerValue number_of_binaries = 10001;</code>
     */
    public function setNumberOfBinaries(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->number_of_binaries = $var;
    }

    /**
     * <pre>
     * Zur "&#64;TreeNodeID" zugehörige ID des Artikel-Elementes
     * </pre>
     *
     * <code>.dstore.values.IntegerValue node_id = 10002;</code>
     */
    public function getNodeId()
    {
        return $this->node_id;
    }

    /**
     * <pre>
     * Zur "&#64;TreeNodeID" zugehörige ID des Artikel-Elementes
     * </pre>
     *
     * <code>.dstore.values.IntegerValue node_id = 10002;</code>
     */
    public function setNodeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->node_id = $var;
    }

}

