<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/om_ModifyPaymentForShipping_Ad.proto

namespace Dstore\Engine\Om_ModifyPaymentForShipping_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.om_ModifyPaymentForShipping_Ad.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.dstore.values.IntegerValue payment_for_shipping_id = 1;</code>
     */
    private $payment_for_shipping_id = null;
    /**
     * <code>bool payment_for_shipping_id_null = 1001;</code>
     */
    private $payment_for_shipping_id_null = false;
    /**
     * <code>.dstore.values.IntegerValue shipping_type_id = 2;</code>
     */
    private $shipping_type_id = null;
    /**
     * <code>bool shipping_type_id_null = 1002;</code>
     */
    private $shipping_type_id_null = false;
    /**
     * <code>.dstore.values.IntegerValue payment_type_id = 3;</code>
     */
    private $payment_type_id = null;
    /**
     * <code>bool payment_type_id_null = 1003;</code>
     */
    private $payment_type_id_null = false;
    /**
     * <code>.dstore.values.StringValue payment_for_shipping_description = 4;</code>
     */
    private $payment_for_shipping_description = null;
    /**
     * <code>bool payment_for_shipping_description_null = 1004;</code>
     */
    private $payment_for_shipping_description_null = false;
    /**
     * <code>.dstore.values.BooleanValue delete_payment_for_shipping = 5;</code>
     */
    private $delete_payment_for_shipping = null;
    /**
     * <code>bool delete_payment_for_shipping_null = 1005;</code>
     */
    private $delete_payment_for_shipping_null = false;
    /**
     * <code>.dstore.values.StringValue description_for_admin = 6;</code>
     */
    private $description_for_admin = null;
    /**
     * <code>bool description_for_admin_null = 1006;</code>
     */
    private $description_for_admin_null = false;
    /**
     * <code>.dstore.values.BooleanValue force_del_or_modify = 7;</code>
     */
    private $force_del_or_modify = null;
    /**
     * <code>bool force_del_or_modify_null = 1007;</code>
     */
    private $force_del_or_modify_null = false;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\OmModifyPaymentForShippingAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>.dstore.values.IntegerValue payment_for_shipping_id = 1;</code>
     */
    public function getPaymentForShippingId()
    {
        return $this->payment_for_shipping_id;
    }

    /**
     * <code>.dstore.values.IntegerValue payment_for_shipping_id = 1;</code>
     */
    public function setPaymentForShippingId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->payment_for_shipping_id = $var;
    }

    /**
     * <code>bool payment_for_shipping_id_null = 1001;</code>
     */
    public function getPaymentForShippingIdNull()
    {
        return $this->payment_for_shipping_id_null;
    }

    /**
     * <code>bool payment_for_shipping_id_null = 1001;</code>
     */
    public function setPaymentForShippingIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->payment_for_shipping_id_null = $var;
    }

    /**
     * <code>.dstore.values.IntegerValue shipping_type_id = 2;</code>
     */
    public function getShippingTypeId()
    {
        return $this->shipping_type_id;
    }

    /**
     * <code>.dstore.values.IntegerValue shipping_type_id = 2;</code>
     */
    public function setShippingTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->shipping_type_id = $var;
    }

    /**
     * <code>bool shipping_type_id_null = 1002;</code>
     */
    public function getShippingTypeIdNull()
    {
        return $this->shipping_type_id_null;
    }

    /**
     * <code>bool shipping_type_id_null = 1002;</code>
     */
    public function setShippingTypeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->shipping_type_id_null = $var;
    }

    /**
     * <code>.dstore.values.IntegerValue payment_type_id = 3;</code>
     */
    public function getPaymentTypeId()
    {
        return $this->payment_type_id;
    }

    /**
     * <code>.dstore.values.IntegerValue payment_type_id = 3;</code>
     */
    public function setPaymentTypeId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->payment_type_id = $var;
    }

    /**
     * <code>bool payment_type_id_null = 1003;</code>
     */
    public function getPaymentTypeIdNull()
    {
        return $this->payment_type_id_null;
    }

    /**
     * <code>bool payment_type_id_null = 1003;</code>
     */
    public function setPaymentTypeIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->payment_type_id_null = $var;
    }

    /**
     * <code>.dstore.values.StringValue payment_for_shipping_description = 4;</code>
     */
    public function getPaymentForShippingDescription()
    {
        return $this->payment_for_shipping_description;
    }

    /**
     * <code>.dstore.values.StringValue payment_for_shipping_description = 4;</code>
     */
    public function setPaymentForShippingDescription(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->payment_for_shipping_description = $var;
    }

    /**
     * <code>bool payment_for_shipping_description_null = 1004;</code>
     */
    public function getPaymentForShippingDescriptionNull()
    {
        return $this->payment_for_shipping_description_null;
    }

    /**
     * <code>bool payment_for_shipping_description_null = 1004;</code>
     */
    public function setPaymentForShippingDescriptionNull($var)
    {
        GPBUtil::checkBool($var);
        $this->payment_for_shipping_description_null = $var;
    }

    /**
     * <code>.dstore.values.BooleanValue delete_payment_for_shipping = 5;</code>
     */
    public function getDeletePaymentForShipping()
    {
        return $this->delete_payment_for_shipping;
    }

    /**
     * <code>.dstore.values.BooleanValue delete_payment_for_shipping = 5;</code>
     */
    public function setDeletePaymentForShipping(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\BooleanValue::class);
        $this->delete_payment_for_shipping = $var;
    }

    /**
     * <code>bool delete_payment_for_shipping_null = 1005;</code>
     */
    public function getDeletePaymentForShippingNull()
    {
        return $this->delete_payment_for_shipping_null;
    }

    /**
     * <code>bool delete_payment_for_shipping_null = 1005;</code>
     */
    public function setDeletePaymentForShippingNull($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_payment_for_shipping_null = $var;
    }

    /**
     * <code>.dstore.values.StringValue description_for_admin = 6;</code>
     */
    public function getDescriptionForAdmin()
    {
        return $this->description_for_admin;
    }

    /**
     * <code>.dstore.values.StringValue description_for_admin = 6;</code>
     */
    public function setDescriptionForAdmin(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->description_for_admin = $var;
    }

    /**
     * <code>bool description_for_admin_null = 1006;</code>
     */
    public function getDescriptionForAdminNull()
    {
        return $this->description_for_admin_null;
    }

    /**
     * <code>bool description_for_admin_null = 1006;</code>
     */
    public function setDescriptionForAdminNull($var)
    {
        GPBUtil::checkBool($var);
        $this->description_for_admin_null = $var;
    }

    /**
     * <code>.dstore.values.BooleanValue force_del_or_modify = 7;</code>
     */
    public function getForceDelOrModify()
    {
        return $this->force_del_or_modify;
    }

    /**
     * <code>.dstore.values.BooleanValue force_del_or_modify = 7;</code>
     */
    public function setForceDelOrModify(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\BooleanValue::class);
        $this->force_del_or_modify = $var;
    }

    /**
     * <code>bool force_del_or_modify_null = 1007;</code>
     */
    public function getForceDelOrModifyNull()
    {
        return $this->force_del_or_modify_null;
    }

    /**
     * <code>bool force_del_or_modify_null = 1007;</code>
     */
    public function setForceDelOrModifyNull($var)
    {
        GPBUtil::checkBool($var);
        $this->force_del_or_modify_null = $var;
    }

}

