<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: dstore/engine/procedures/om_ModifyPurchaseOrderTypes_Ad.proto
//   Date: 2015-08-17 11:45:23

namespace dstore\engine\om_ModifyPurchaseOrderTypes_Ad {

  class Parameters extends \DrSlump\Protobuf\Message {

    /**  @var \dstore\engine\values\integerValue */
    public $order_type_id = null;
    
    /**  @var boolean */
    public $order_type_id_null = null;
    
    /**  @var \dstore\engine\values\stringValue */
    public $order_type_description = null;
    
    /**  @var boolean */
    public $order_type_description_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $delete_order_type = null;
    
    /**  @var boolean */
    public $delete_order_type_null = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'dstore.engine.om_ModifyPurchaseOrderTypes_Ad.Parameters');

      // OPTIONAL MESSAGE order_type_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "order_type_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL order_type_id_null = 1001
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1001;
      $f->name      = "order_type_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE order_type_description = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "order_type_description";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL order_type_description_null = 1002
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1002;
      $f->name      = "order_type_description_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE delete_order_type = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "delete_order_type";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL delete_order_type_null = 1003
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1003;
      $f->name      = "delete_order_type_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <order_type_id> has a value
     *
     * @return boolean
     */
    public function hasOrderTypeId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <order_type_id> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearOrderTypeId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <order_type_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getOrderTypeId(){
      return $this->_get(1);
    }
    
    /**
     * Set <order_type_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setOrderTypeId(\dstore\engine\values\integerValue $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <order_type_id_null> has a value
     *
     * @return boolean
     */
    public function hasOrderTypeIdNull(){
      return $this->_has(1001);
    }
    
    /**
     * Clear <order_type_id_null> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearOrderTypeIdNull(){
      return $this->_clear(1001);
    }
    
    /**
     * Get <order_type_id_null> value
     *
     * @return boolean
     */
    public function getOrderTypeIdNull(){
      return $this->_get(1001);
    }
    
    /**
     * Set <order_type_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setOrderTypeIdNull( $value){
      return $this->_set(1001, $value);
    }
    
    /**
     * Check if <order_type_description> has a value
     *
     * @return boolean
     */
    public function hasOrderTypeDescription(){
      return $this->_has(2);
    }
    
    /**
     * Clear <order_type_description> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearOrderTypeDescription(){
      return $this->_clear(2);
    }
    
    /**
     * Get <order_type_description> value
     *
     * @return \dstore\engine\values\stringValue
     */
    public function getOrderTypeDescription(){
      return $this->_get(2);
    }
    
    /**
     * Set <order_type_description> value
     *
     * @param \dstore\engine\values\stringValue $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setOrderTypeDescription(\dstore\engine\values\stringValue $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <order_type_description_null> has a value
     *
     * @return boolean
     */
    public function hasOrderTypeDescriptionNull(){
      return $this->_has(1002);
    }
    
    /**
     * Clear <order_type_description_null> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearOrderTypeDescriptionNull(){
      return $this->_clear(1002);
    }
    
    /**
     * Get <order_type_description_null> value
     *
     * @return boolean
     */
    public function getOrderTypeDescriptionNull(){
      return $this->_get(1002);
    }
    
    /**
     * Set <order_type_description_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setOrderTypeDescriptionNull( $value){
      return $this->_set(1002, $value);
    }
    
    /**
     * Check if <delete_order_type> has a value
     *
     * @return boolean
     */
    public function hasDeleteOrderType(){
      return $this->_has(3);
    }
    
    /**
     * Clear <delete_order_type> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearDeleteOrderType(){
      return $this->_clear(3);
    }
    
    /**
     * Get <delete_order_type> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getDeleteOrderType(){
      return $this->_get(3);
    }
    
    /**
     * Set <delete_order_type> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setDeleteOrderType(\dstore\engine\values\booleanValue $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <delete_order_type_null> has a value
     *
     * @return boolean
     */
    public function hasDeleteOrderTypeNull(){
      return $this->_has(1003);
    }
    
    /**
     * Clear <delete_order_type_null> value
     *
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function clearDeleteOrderTypeNull(){
      return $this->_clear(1003);
    }
    
    /**
     * Get <delete_order_type_null> value
     *
     * @return boolean
     */
    public function getDeleteOrderTypeNull(){
      return $this->_get(1003);
    }
    
    /**
     * Set <delete_order_type_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_ModifyPurchaseOrderTypes_Ad\Parameters
     */
    public function setDeleteOrderTypeNull( $value){
      return $this->_set(1003, $value);
    }
  }
}

