<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/om_GetCamPeriodStatusValues_Ad.proto

namespace Dstore\Engine\Om_GetCamPeriodStatusValues_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.om_GetCamPeriodStatusValues_Ad.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\OmGetCamPeriodStatusValuesAd::initOnce();
        parent::__construct();
    }

}

