<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/elastic/item/suggest.proto

namespace Dstore\Elastic\Suggest;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Request extends \Google\Protobuf\Internal\Message
{
    private $input = '';
    private $field_name;
    private $base_query = null;
    private $max_items = 0;
    private $max_suggests = 0;
    private $fuzzy = false;
    private $use_and_operator = false;

    public function getInput()
    {
        return $this->input;
    }

    public function setInput($var)
    {
        GPBUtil::checkString($var, True);
        $this->input = $var;
    }

    public function getFieldName()
    {
        return $this->field_name;
    }

    public function setFieldName(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::STRING);
        $this->field_name = $var;
    }

    public function getBaseQuery()
    {
        return $this->base_query;
    }

    public function setBaseQuery(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Elastic\BoolQuery::class);
        $this->base_query = $var;
    }

    public function getMaxItems()
    {
        return $this->max_items;
    }

    public function setMaxItems($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_items = $var;
    }

    public function getMaxSuggests()
    {
        return $this->max_suggests;
    }

    public function setMaxSuggests($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_suggests = $var;
    }

    public function getFuzzy()
    {
        return $this->fuzzy;
    }

    public function setFuzzy($var)
    {
        GPBUtil::checkBool($var);
        $this->fuzzy = $var;
    }

    public function getUseAndOperator()
    {
        return $this->use_and_operator;
    }

    public function setUseAndOperator($var)
    {
        GPBUtil::checkBool($var);
        $this->use_and_operator = $var;
    }

}

class Response extends \Google\Protobuf\Internal\Message
{
    private $suggestion;
    private $matching_item;
    private $elastic_query_string = '';

    public function getSuggestion()
    {
        return $this->suggestion;
    }

    public function setSuggestion(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Elastic\Suggest\Response_Suggestion::class);
        $this->suggestion = $var;
    }

    public function getMatchingItem()
    {
        return $this->matching_item;
    }

    public function setMatchingItem(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Dstore\Elastic\Item\Item::class);
        $this->matching_item = $var;
    }

    public function getElasticQueryString()
    {
        return $this->elastic_query_string;
    }

    public function setElasticQueryString($var)
    {
        GPBUtil::checkString($var, True);
        $this->elastic_query_string = $var;
    }

}

class Response_Suggestion extends \Google\Protobuf\Internal\Message
{
    private $field_name = '';
    private $count = 0;
    private $value = '';

    public function getFieldName()
    {
        return $this->field_name;
    }

    public function setFieldName($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_name = $var;
    }

    public function getCount()
    {
        return $this->count;
    }

    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ad8040a216473746f72652f656c61737469632f6974656d2f7375676765" .
    "73742e70726f746f12166473746f72652e656c61737469632e7375676765" .
    "73741a1c6473746f72652f656c61737469632f656c61737469632e70726f" .
    "746f1a1e6473746f72652f656c61737469632f6974656d2f6974656d2e70" .
    "726f746f22ad010a0752657175657374120d0a05696e7075741801200128" .
    "0912120a0a6669656c645f6e616d65180220032809122d0a0a626173655f" .
    "717565727918032001280b32192e6473746f72652e656c61737469632e42" .
    "6f6f6c517565727912110a096d61785f6974656d7318052001280512140a" .
    "0c6d61785f7375676765737473180620012805120d0a0566757a7a791807" .
    "2001280812180a107573655f616e645f6f70657261746f72180820012808" .
    "22db010a08526573706f6e7365123f0a0a73756767657374696f6e180220" .
    "03280b322b2e6473746f72652e656c61737469632e737567676573742e52" .
    "6573706f6e73652e53756767657374696f6e12300a0d6d61746368696e67" .
    "5f6974656d18032003280b32192e6473746f72652e656c61737469632e69" .
    "74656d2e4974656d121c0a14656c61737469635f71756572795f73747269" .
    "6e671805200128091a3e0a0a53756767657374696f6e12120a0a6669656c" .
    "645f6e616d65180120012809120d0a05636f756e74180220012805120d0a" .
    "0576616c756518032001280942470a16696f2e6473746f72652e656c6173" .
    "7469632e6974656d4207537567676573745a24676f73646b2e6473746f72" .
    "652e64652f656c61737469632f6974656d2f73756767657374620670726f" .
    "746f33"
));

