<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: dstore/engine/procedures/om_GetRequiredInfoForPay_Ad.proto
//   Date: 2016-05-19 08:07:50

namespace dstore\engine\om_GetRequiredInfoForPay_Ad\Response {

  class Row extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $row_id = null;
    
    /**  @var \dstore\values\integerValue */
    public $payment_for_shipping_id = null;
    
    /**  @var \dstore\values\stringValue */
    public $category_description = null;
    
    /**  @var \dstore\values\stringValue */
    public $payment_for_shipping_description = null;
    
    /**  @var \dstore\values\integerValue */
    public $person_charac_category_id = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'dstore.engine.om_GetRequiredInfoForPay_Ad.Response.Row');

      // OPTIONAL INT32 row_id = 10000
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10000;
      $f->name      = "row_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE payment_for_shipping_id = 10001
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10001;
      $f->name      = "payment_for_shipping_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE category_description = 10002
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10002;
      $f->name      = "category_description";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE payment_for_shipping_description = 10003
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10003;
      $f->name      = "payment_for_shipping_description";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL MESSAGE person_charac_category_id = 10004
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10004;
      $f->name      = "person_charac_category_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\values\integerValue';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <row_id> has a value
     *
     * @return boolean
     */
    public function hasRowId(){
      return $this->_has(10000);
    }
    
    /**
     * Clear <row_id> value
     *
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function clearRowId(){
      return $this->_clear(10000);
    }
    
    /**
     * Get <row_id> value
     *
     * @return int
     */
    public function getRowId(){
      return $this->_get(10000);
    }
    
    /**
     * Set <row_id> value
     *
     * @param int $value
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function setRowId( $value){
      return $this->_set(10000, $value);
    }
    
    /**
     * Check if <payment_for_shipping_id> has a value
     *
     * @return boolean
     */
    public function hasPaymentForShippingId(){
      return $this->_has(10001);
    }
    
    /**
     * Clear <payment_for_shipping_id> value
     *
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function clearPaymentForShippingId(){
      return $this->_clear(10001);
    }
    
    /**
     * Get <payment_for_shipping_id> value
     *
     * @return \dstore\values\integerValue
     */
    public function getPaymentForShippingId(){
      return $this->_get(10001);
    }
    
    /**
     * Set <payment_for_shipping_id> value
     *
     * @param \dstore\values\integerValue $value
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function setPaymentForShippingId(\dstore\values\integerValue $value){
      return $this->_set(10001, $value);
    }
    
    /**
     * Check if <category_description> has a value
     *
     * @return boolean
     */
    public function hasCategoryDescription(){
      return $this->_has(10002);
    }
    
    /**
     * Clear <category_description> value
     *
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function clearCategoryDescription(){
      return $this->_clear(10002);
    }
    
    /**
     * Get <category_description> value
     *
     * @return \dstore\values\stringValue
     */
    public function getCategoryDescription(){
      return $this->_get(10002);
    }
    
    /**
     * Set <category_description> value
     *
     * @param \dstore\values\stringValue $value
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function setCategoryDescription(\dstore\values\stringValue $value){
      return $this->_set(10002, $value);
    }
    
    /**
     * Check if <payment_for_shipping_description> has a value
     *
     * @return boolean
     */
    public function hasPaymentForShippingDescription(){
      return $this->_has(10003);
    }
    
    /**
     * Clear <payment_for_shipping_description> value
     *
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function clearPaymentForShippingDescription(){
      return $this->_clear(10003);
    }
    
    /**
     * Get <payment_for_shipping_description> value
     *
     * @return \dstore\values\stringValue
     */
    public function getPaymentForShippingDescription(){
      return $this->_get(10003);
    }
    
    /**
     * Set <payment_for_shipping_description> value
     *
     * @param \dstore\values\stringValue $value
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function setPaymentForShippingDescription(\dstore\values\stringValue $value){
      return $this->_set(10003, $value);
    }
    
    /**
     * Check if <person_charac_category_id> has a value
     *
     * @return boolean
     */
    public function hasPersonCharacCategoryId(){
      return $this->_has(10004);
    }
    
    /**
     * Clear <person_charac_category_id> value
     *
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function clearPersonCharacCategoryId(){
      return $this->_clear(10004);
    }
    
    /**
     * Get <person_charac_category_id> value
     *
     * @return \dstore\values\integerValue
     */
    public function getPersonCharacCategoryId(){
      return $this->_get(10004);
    }
    
    /**
     * Set <person_charac_category_id> value
     *
     * @param \dstore\values\integerValue $value
     * @return \dstore\engine\om_GetRequiredInfoForPay_Ad\Response\Row
     */
    public function setPersonCharacCategoryId(\dstore\values\integerValue $value){
      return $this->_set(10004, $value);
    }
  }
}

