<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/do_GetdStoreVersions_Ad.proto

namespace Dstore\Engine\Do_GetdStoreVersions_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.do_GetdStoreVersions_Ad.Response.Row</code>
 */
class Response_Row extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 row_id = 10000;</code>
     */
    private $row_id = 0;
    /**
     * <pre>
     * Bestimmt die Reihenfolge von "dStoreVersion" innerhalb aller dStore-Versionen
     * </pre>
     *
     * <code>.dstore.values.IntegerValue version_sort_no = 10001;</code>
     */
    private $version_sort_no = null;
    /**
     * <pre>
     * Eine "dStore"-Versionsnummer (von der Form "3.5.17"), die bereits veröffentlicht wurde bzw. zu der es für "&#64;ProcedureName" eine Dokumentation gibt
     * </pre>
     *
     * <code>.dstore.values.StringValue dstore_version = 10002;</code>
     */
    private $dstore_version = null;
    /**
     * <pre>
     * Release-Datum der Version
     * </pre>
     *
     * <code>.dstore.values.TimestampValue release_date_and_time = 10003;</code>
     */
    private $release_date_and_time = null;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\DoGetdStoreVersionsAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function getRowId()
    {
        return $this->row_id;
    }

    /**
     * <code>int32 row_id = 10000;</code>
     */
    public function setRowId($var)
    {
        GPBUtil::checkInt32($var);
        $this->row_id = $var;
    }

    /**
     * <pre>
     * Bestimmt die Reihenfolge von "dStoreVersion" innerhalb aller dStore-Versionen
     * </pre>
     *
     * <code>.dstore.values.IntegerValue version_sort_no = 10001;</code>
     */
    public function getVersionSortNo()
    {
        return $this->version_sort_no;
    }

    /**
     * <pre>
     * Bestimmt die Reihenfolge von "dStoreVersion" innerhalb aller dStore-Versionen
     * </pre>
     *
     * <code>.dstore.values.IntegerValue version_sort_no = 10001;</code>
     */
    public function setVersionSortNo(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->version_sort_no = $var;
    }

    /**
     * <pre>
     * Eine "dStore"-Versionsnummer (von der Form "3.5.17"), die bereits veröffentlicht wurde bzw. zu der es für "&#64;ProcedureName" eine Dokumentation gibt
     * </pre>
     *
     * <code>.dstore.values.StringValue dstore_version = 10002;</code>
     */
    public function getDstoreVersion()
    {
        return $this->dstore_version;
    }

    /**
     * <pre>
     * Eine "dStore"-Versionsnummer (von der Form "3.5.17"), die bereits veröffentlicht wurde bzw. zu der es für "&#64;ProcedureName" eine Dokumentation gibt
     * </pre>
     *
     * <code>.dstore.values.StringValue dstore_version = 10002;</code>
     */
    public function setDstoreVersion(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\StringValue::class);
        $this->dstore_version = $var;
    }

    /**
     * <pre>
     * Release-Datum der Version
     * </pre>
     *
     * <code>.dstore.values.TimestampValue release_date_and_time = 10003;</code>
     */
    public function getReleaseDateAndTime()
    {
        return $this->release_date_and_time;
    }

    /**
     * <pre>
     * Release-Datum der Version
     * </pre>
     *
     * <code>.dstore.values.TimestampValue release_date_and_time = 10003;</code>
     */
    public function setReleaseDateAndTime(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\TimestampValue::class);
        $this->release_date_and_time = $var;
    }

}

