<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/im_GetRootNodes_Ad.proto

namespace Dstore\Engine\Im_GetRootNodes_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.im_GetRootNodes_Ad.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.dstore.values.BooleanValue only_active = 1;</code>
     */
    private $only_active = null;
    /**
     * <code>bool only_active_null = 1001;</code>
     */
    private $only_active_null = false;
    /**
     * <code>.dstore.values.BooleanValue only_not_deleted = 2;</code>
     */
    private $only_not_deleted = null;
    /**
     * <code>bool only_not_deleted_null = 1002;</code>
     */
    private $only_not_deleted_null = false;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\ImGetRootNodesAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>.dstore.values.BooleanValue only_active = 1;</code>
     */
    public function getOnlyActive()
    {
        return $this->only_active;
    }

    /**
     * <code>.dstore.values.BooleanValue only_active = 1;</code>
     */
    public function setOnlyActive(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\BooleanValue::class);
        $this->only_active = $var;
    }

    /**
     * <code>bool only_active_null = 1001;</code>
     */
    public function getOnlyActiveNull()
    {
        return $this->only_active_null;
    }

    /**
     * <code>bool only_active_null = 1001;</code>
     */
    public function setOnlyActiveNull($var)
    {
        GPBUtil::checkBool($var);
        $this->only_active_null = $var;
    }

    /**
     * <code>.dstore.values.BooleanValue only_not_deleted = 2;</code>
     */
    public function getOnlyNotDeleted()
    {
        return $this->only_not_deleted;
    }

    /**
     * <code>.dstore.values.BooleanValue only_not_deleted = 2;</code>
     */
    public function setOnlyNotDeleted(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\BooleanValue::class);
        $this->only_not_deleted = $var;
    }

    /**
     * <code>bool only_not_deleted_null = 1002;</code>
     */
    public function getOnlyNotDeletedNull()
    {
        return $this->only_not_deleted_null;
    }

    /**
     * <code>bool only_not_deleted_null = 1002;</code>
     */
    public function setOnlyNotDeletedNull($var)
    {
        GPBUtil::checkBool($var);
        $this->only_not_deleted_null = $var;
    }

}

