<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/elastic/elastic.proto

namespace Dstore\Elastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.elastic.Range</code>
 */
class Range extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string from = 1;</code>
     */
    private $from = '';
    /**
     * <code>string to = 2;</code>
     */
    private $to = '';

    public function __construct() {
        \GPBMetadata\Dstore\Elastic\Elastic::initOnce();
        parent::__construct();
    }

    /**
     * <code>string from = 1;</code>
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * <code>string from = 1;</code>
     */
    public function setFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->from = $var;
    }

    /**
     * <code>string to = 2;</code>
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * <code>string to = 2;</code>
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;
    }

}

