<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: dstore/engine/procedures/om_GetOrders_Pu.proto
//   Date: 2015-10-06 11:19:58

namespace dstore\engine\om_GetOrders_Pu {

  class Parameters extends \DrSlump\Protobuf\Message {

    /**  @var \dstore\engine\values\booleanValue */
    public $get_a_certain_order = null;
    
    /**  @var boolean */
    public $get_a_certain_order_null = null;
    
    /**  @var \dstore\engine\values\stringValue */
    public $person_identification_values = null;
    
    /**  @var boolean */
    public $person_identification_values_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $person_type_id = null;
    
    /**  @var boolean */
    public $person_type_id_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $date_and_time_format = null;
    
    /**  @var boolean */
    public $date_and_time_format_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $include_time = null;
    
    /**  @var boolean */
    public $include_time_null = null;
    
    /**  @var \dstore\engine\values\timestampValue */
    public $from_date = null;
    
    /**  @var boolean */
    public $from_date_null = null;
    
    /**  @var \dstore\engine\values\timestampValue */
    public $to_date = null;
    
    /**  @var boolean */
    public $to_date_null = null;
    
    /**  @var \dstore\engine\values\stringValue */
    public $order_state_list = null;
    
    /**  @var boolean */
    public $order_state_list_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $skip_o_having_different_o_states = null;
    
    /**  @var boolean */
    public $skip_o_having_different_o_states_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $order_id = null;
    
    /**  @var boolean */
    public $order_id_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $rowcount = null;
    
    /**  @var boolean */
    public $rowcount_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $case_sensitive = null;
    
    /**  @var boolean */
    public $case_sensitive_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $include_item_no = null;
    
    /**  @var boolean */
    public $include_item_no_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $order_desc = null;
    
    /**  @var boolean */
    public $order_desc_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $information_type_id = null;
    
    /**  @var boolean */
    public $information_type_id_null = null;
    
    /**  @var \dstore\engine\values\stringValue */
    public $information = null;
    
    /**  @var boolean */
    public $information_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $node_characteristic_id = null;
    
    /**  @var boolean */
    public $node_characteristic_id_null = null;
    
    /**  @var \dstore\engine\values\integerValue */
    public $language_id = null;
    
    /**  @var boolean */
    public $language_id_null = null;
    
    /**  @var \dstore\engine\values\booleanValue */
    public $purchase_order = null;
    
    /**  @var boolean */
    public $purchase_order_null = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'dstore.engine.om_GetOrders_Pu.Parameters');

      // OPTIONAL MESSAGE get_a_certain_order = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "get_a_certain_order";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL get_a_certain_order_null = 1001
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1001;
      $f->name      = "get_a_certain_order_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE person_identification_values = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "person_identification_values";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL person_identification_values_null = 1002
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1002;
      $f->name      = "person_identification_values_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE person_type_id = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "person_type_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL person_type_id_null = 1003
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1003;
      $f->name      = "person_type_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE date_and_time_format = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "date_and_time_format";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL date_and_time_format_null = 1004
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1004;
      $f->name      = "date_and_time_format_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE include_time = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "include_time";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL include_time_null = 1005
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1005;
      $f->name      = "include_time_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE from_date = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "from_date";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\timestampValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL from_date_null = 1006
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1006;
      $f->name      = "from_date_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE to_date = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "to_date";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\timestampValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL to_date_null = 1007
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1007;
      $f->name      = "to_date_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE order_state_list = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "order_state_list";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL order_state_list_null = 1008
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1008;
      $f->name      = "order_state_list_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE skip_o_having_different_o_states = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "skip_o_having_different_o_states";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL skip_o_having_different_o_states_null = 1009
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1009;
      $f->name      = "skip_o_having_different_o_states_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE order_id = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "order_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL order_id_null = 1010
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1010;
      $f->name      = "order_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE rowcount = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "rowcount";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL rowcount_null = 1011
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1011;
      $f->name      = "rowcount_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE case_sensitive = 12
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 12;
      $f->name      = "case_sensitive";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL case_sensitive_null = 1012
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1012;
      $f->name      = "case_sensitive_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE include_item_no = 13
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 13;
      $f->name      = "include_item_no";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL include_item_no_null = 1013
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1013;
      $f->name      = "include_item_no_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE order_desc = 14
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 14;
      $f->name      = "order_desc";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL order_desc_null = 1014
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1014;
      $f->name      = "order_desc_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE information_type_id = 15
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 15;
      $f->name      = "information_type_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL information_type_id_null = 1015
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1015;
      $f->name      = "information_type_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE information = 16
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 16;
      $f->name      = "information";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\stringValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL information_null = 1016
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1016;
      $f->name      = "information_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE node_characteristic_id = 17
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 17;
      $f->name      = "node_characteristic_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL node_characteristic_id_null = 1017
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1017;
      $f->name      = "node_characteristic_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE language_id = 18
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 18;
      $f->name      = "language_id";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\integerValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL language_id_null = 1018
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1018;
      $f->name      = "language_id_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE purchase_order = 19
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 19;
      $f->name      = "purchase_order";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\dstore\engine\values\booleanValue';
      $descriptor->addField($f);

      // OPTIONAL BOOL purchase_order_null = 1019
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1019;
      $f->name      = "purchase_order_null";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <get_a_certain_order> has a value
     *
     * @return boolean
     */
    public function hasGetACertainOrder(){
      return $this->_has(1);
    }
    
    /**
     * Clear <get_a_certain_order> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearGetACertainOrder(){
      return $this->_clear(1);
    }
    
    /**
     * Get <get_a_certain_order> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getGetACertainOrder(){
      return $this->_get(1);
    }
    
    /**
     * Set <get_a_certain_order> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setGetACertainOrder(\dstore\engine\values\booleanValue $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <get_a_certain_order_null> has a value
     *
     * @return boolean
     */
    public function hasGetACertainOrderNull(){
      return $this->_has(1001);
    }
    
    /**
     * Clear <get_a_certain_order_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearGetACertainOrderNull(){
      return $this->_clear(1001);
    }
    
    /**
     * Get <get_a_certain_order_null> value
     *
     * @return boolean
     */
    public function getGetACertainOrderNull(){
      return $this->_get(1001);
    }
    
    /**
     * Set <get_a_certain_order_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setGetACertainOrderNull( $value){
      return $this->_set(1001, $value);
    }
    
    /**
     * Check if <person_identification_values> has a value
     *
     * @return boolean
     */
    public function hasPersonIdentificationValues(){
      return $this->_has(2);
    }
    
    /**
     * Clear <person_identification_values> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPersonIdentificationValues(){
      return $this->_clear(2);
    }
    
    /**
     * Get <person_identification_values> value
     *
     * @return \dstore\engine\values\stringValue
     */
    public function getPersonIdentificationValues(){
      return $this->_get(2);
    }
    
    /**
     * Set <person_identification_values> value
     *
     * @param \dstore\engine\values\stringValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPersonIdentificationValues(\dstore\engine\values\stringValue $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <person_identification_values_null> has a value
     *
     * @return boolean
     */
    public function hasPersonIdentificationValuesNull(){
      return $this->_has(1002);
    }
    
    /**
     * Clear <person_identification_values_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPersonIdentificationValuesNull(){
      return $this->_clear(1002);
    }
    
    /**
     * Get <person_identification_values_null> value
     *
     * @return boolean
     */
    public function getPersonIdentificationValuesNull(){
      return $this->_get(1002);
    }
    
    /**
     * Set <person_identification_values_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPersonIdentificationValuesNull( $value){
      return $this->_set(1002, $value);
    }
    
    /**
     * Check if <person_type_id> has a value
     *
     * @return boolean
     */
    public function hasPersonTypeId(){
      return $this->_has(3);
    }
    
    /**
     * Clear <person_type_id> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPersonTypeId(){
      return $this->_clear(3);
    }
    
    /**
     * Get <person_type_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getPersonTypeId(){
      return $this->_get(3);
    }
    
    /**
     * Set <person_type_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPersonTypeId(\dstore\engine\values\integerValue $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <person_type_id_null> has a value
     *
     * @return boolean
     */
    public function hasPersonTypeIdNull(){
      return $this->_has(1003);
    }
    
    /**
     * Clear <person_type_id_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPersonTypeIdNull(){
      return $this->_clear(1003);
    }
    
    /**
     * Get <person_type_id_null> value
     *
     * @return boolean
     */
    public function getPersonTypeIdNull(){
      return $this->_get(1003);
    }
    
    /**
     * Set <person_type_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPersonTypeIdNull( $value){
      return $this->_set(1003, $value);
    }
    
    /**
     * Check if <date_and_time_format> has a value
     *
     * @return boolean
     */
    public function hasDateAndTimeFormat(){
      return $this->_has(4);
    }
    
    /**
     * Clear <date_and_time_format> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearDateAndTimeFormat(){
      return $this->_clear(4);
    }
    
    /**
     * Get <date_and_time_format> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getDateAndTimeFormat(){
      return $this->_get(4);
    }
    
    /**
     * Set <date_and_time_format> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setDateAndTimeFormat(\dstore\engine\values\integerValue $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <date_and_time_format_null> has a value
     *
     * @return boolean
     */
    public function hasDateAndTimeFormatNull(){
      return $this->_has(1004);
    }
    
    /**
     * Clear <date_and_time_format_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearDateAndTimeFormatNull(){
      return $this->_clear(1004);
    }
    
    /**
     * Get <date_and_time_format_null> value
     *
     * @return boolean
     */
    public function getDateAndTimeFormatNull(){
      return $this->_get(1004);
    }
    
    /**
     * Set <date_and_time_format_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setDateAndTimeFormatNull( $value){
      return $this->_set(1004, $value);
    }
    
    /**
     * Check if <include_time> has a value
     *
     * @return boolean
     */
    public function hasIncludeTime(){
      return $this->_has(5);
    }
    
    /**
     * Clear <include_time> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearIncludeTime(){
      return $this->_clear(5);
    }
    
    /**
     * Get <include_time> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getIncludeTime(){
      return $this->_get(5);
    }
    
    /**
     * Set <include_time> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setIncludeTime(\dstore\engine\values\booleanValue $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <include_time_null> has a value
     *
     * @return boolean
     */
    public function hasIncludeTimeNull(){
      return $this->_has(1005);
    }
    
    /**
     * Clear <include_time_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearIncludeTimeNull(){
      return $this->_clear(1005);
    }
    
    /**
     * Get <include_time_null> value
     *
     * @return boolean
     */
    public function getIncludeTimeNull(){
      return $this->_get(1005);
    }
    
    /**
     * Set <include_time_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setIncludeTimeNull( $value){
      return $this->_set(1005, $value);
    }
    
    /**
     * Check if <from_date> has a value
     *
     * @return boolean
     */
    public function hasFromDate(){
      return $this->_has(6);
    }
    
    /**
     * Clear <from_date> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearFromDate(){
      return $this->_clear(6);
    }
    
    /**
     * Get <from_date> value
     *
     * @return \dstore\engine\values\timestampValue
     */
    public function getFromDate(){
      return $this->_get(6);
    }
    
    /**
     * Set <from_date> value
     *
     * @param \dstore\engine\values\timestampValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setFromDate(\dstore\engine\values\timestampValue $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <from_date_null> has a value
     *
     * @return boolean
     */
    public function hasFromDateNull(){
      return $this->_has(1006);
    }
    
    /**
     * Clear <from_date_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearFromDateNull(){
      return $this->_clear(1006);
    }
    
    /**
     * Get <from_date_null> value
     *
     * @return boolean
     */
    public function getFromDateNull(){
      return $this->_get(1006);
    }
    
    /**
     * Set <from_date_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setFromDateNull( $value){
      return $this->_set(1006, $value);
    }
    
    /**
     * Check if <to_date> has a value
     *
     * @return boolean
     */
    public function hasToDate(){
      return $this->_has(7);
    }
    
    /**
     * Clear <to_date> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearToDate(){
      return $this->_clear(7);
    }
    
    /**
     * Get <to_date> value
     *
     * @return \dstore\engine\values\timestampValue
     */
    public function getToDate(){
      return $this->_get(7);
    }
    
    /**
     * Set <to_date> value
     *
     * @param \dstore\engine\values\timestampValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setToDate(\dstore\engine\values\timestampValue $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <to_date_null> has a value
     *
     * @return boolean
     */
    public function hasToDateNull(){
      return $this->_has(1007);
    }
    
    /**
     * Clear <to_date_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearToDateNull(){
      return $this->_clear(1007);
    }
    
    /**
     * Get <to_date_null> value
     *
     * @return boolean
     */
    public function getToDateNull(){
      return $this->_get(1007);
    }
    
    /**
     * Set <to_date_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setToDateNull( $value){
      return $this->_set(1007, $value);
    }
    
    /**
     * Check if <order_state_list> has a value
     *
     * @return boolean
     */
    public function hasOrderStateList(){
      return $this->_has(8);
    }
    
    /**
     * Clear <order_state_list> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderStateList(){
      return $this->_clear(8);
    }
    
    /**
     * Get <order_state_list> value
     *
     * @return \dstore\engine\values\stringValue
     */
    public function getOrderStateList(){
      return $this->_get(8);
    }
    
    /**
     * Set <order_state_list> value
     *
     * @param \dstore\engine\values\stringValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderStateList(\dstore\engine\values\stringValue $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <order_state_list_null> has a value
     *
     * @return boolean
     */
    public function hasOrderStateListNull(){
      return $this->_has(1008);
    }
    
    /**
     * Clear <order_state_list_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderStateListNull(){
      return $this->_clear(1008);
    }
    
    /**
     * Get <order_state_list_null> value
     *
     * @return boolean
     */
    public function getOrderStateListNull(){
      return $this->_get(1008);
    }
    
    /**
     * Set <order_state_list_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderStateListNull( $value){
      return $this->_set(1008, $value);
    }
    
    /**
     * Check if <skip_o_having_different_o_states> has a value
     *
     * @return boolean
     */
    public function hasSkipOHavingDifferentOStates(){
      return $this->_has(9);
    }
    
    /**
     * Clear <skip_o_having_different_o_states> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearSkipOHavingDifferentOStates(){
      return $this->_clear(9);
    }
    
    /**
     * Get <skip_o_having_different_o_states> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getSkipOHavingDifferentOStates(){
      return $this->_get(9);
    }
    
    /**
     * Set <skip_o_having_different_o_states> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setSkipOHavingDifferentOStates(\dstore\engine\values\booleanValue $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <skip_o_having_different_o_states_null> has a value
     *
     * @return boolean
     */
    public function hasSkipOHavingDifferentOStatesNull(){
      return $this->_has(1009);
    }
    
    /**
     * Clear <skip_o_having_different_o_states_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearSkipOHavingDifferentOStatesNull(){
      return $this->_clear(1009);
    }
    
    /**
     * Get <skip_o_having_different_o_states_null> value
     *
     * @return boolean
     */
    public function getSkipOHavingDifferentOStatesNull(){
      return $this->_get(1009);
    }
    
    /**
     * Set <skip_o_having_different_o_states_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setSkipOHavingDifferentOStatesNull( $value){
      return $this->_set(1009, $value);
    }
    
    /**
     * Check if <order_id> has a value
     *
     * @return boolean
     */
    public function hasOrderId(){
      return $this->_has(10);
    }
    
    /**
     * Clear <order_id> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderId(){
      return $this->_clear(10);
    }
    
    /**
     * Get <order_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getOrderId(){
      return $this->_get(10);
    }
    
    /**
     * Set <order_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderId(\dstore\engine\values\integerValue $value){
      return $this->_set(10, $value);
    }
    
    /**
     * Check if <order_id_null> has a value
     *
     * @return boolean
     */
    public function hasOrderIdNull(){
      return $this->_has(1010);
    }
    
    /**
     * Clear <order_id_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderIdNull(){
      return $this->_clear(1010);
    }
    
    /**
     * Get <order_id_null> value
     *
     * @return boolean
     */
    public function getOrderIdNull(){
      return $this->_get(1010);
    }
    
    /**
     * Set <order_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderIdNull( $value){
      return $this->_set(1010, $value);
    }
    
    /**
     * Check if <rowcount> has a value
     *
     * @return boolean
     */
    public function hasRowcount(){
      return $this->_has(11);
    }
    
    /**
     * Clear <rowcount> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearRowcount(){
      return $this->_clear(11);
    }
    
    /**
     * Get <rowcount> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getRowcount(){
      return $this->_get(11);
    }
    
    /**
     * Set <rowcount> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setRowcount(\dstore\engine\values\integerValue $value){
      return $this->_set(11, $value);
    }
    
    /**
     * Check if <rowcount_null> has a value
     *
     * @return boolean
     */
    public function hasRowcountNull(){
      return $this->_has(1011);
    }
    
    /**
     * Clear <rowcount_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearRowcountNull(){
      return $this->_clear(1011);
    }
    
    /**
     * Get <rowcount_null> value
     *
     * @return boolean
     */
    public function getRowcountNull(){
      return $this->_get(1011);
    }
    
    /**
     * Set <rowcount_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setRowcountNull( $value){
      return $this->_set(1011, $value);
    }
    
    /**
     * Check if <case_sensitive> has a value
     *
     * @return boolean
     */
    public function hasCaseSensitive(){
      return $this->_has(12);
    }
    
    /**
     * Clear <case_sensitive> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearCaseSensitive(){
      return $this->_clear(12);
    }
    
    /**
     * Get <case_sensitive> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getCaseSensitive(){
      return $this->_get(12);
    }
    
    /**
     * Set <case_sensitive> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setCaseSensitive(\dstore\engine\values\booleanValue $value){
      return $this->_set(12, $value);
    }
    
    /**
     * Check if <case_sensitive_null> has a value
     *
     * @return boolean
     */
    public function hasCaseSensitiveNull(){
      return $this->_has(1012);
    }
    
    /**
     * Clear <case_sensitive_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearCaseSensitiveNull(){
      return $this->_clear(1012);
    }
    
    /**
     * Get <case_sensitive_null> value
     *
     * @return boolean
     */
    public function getCaseSensitiveNull(){
      return $this->_get(1012);
    }
    
    /**
     * Set <case_sensitive_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setCaseSensitiveNull( $value){
      return $this->_set(1012, $value);
    }
    
    /**
     * Check if <include_item_no> has a value
     *
     * @return boolean
     */
    public function hasIncludeItemNo(){
      return $this->_has(13);
    }
    
    /**
     * Clear <include_item_no> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearIncludeItemNo(){
      return $this->_clear(13);
    }
    
    /**
     * Get <include_item_no> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getIncludeItemNo(){
      return $this->_get(13);
    }
    
    /**
     * Set <include_item_no> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setIncludeItemNo(\dstore\engine\values\booleanValue $value){
      return $this->_set(13, $value);
    }
    
    /**
     * Check if <include_item_no_null> has a value
     *
     * @return boolean
     */
    public function hasIncludeItemNoNull(){
      return $this->_has(1013);
    }
    
    /**
     * Clear <include_item_no_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearIncludeItemNoNull(){
      return $this->_clear(1013);
    }
    
    /**
     * Get <include_item_no_null> value
     *
     * @return boolean
     */
    public function getIncludeItemNoNull(){
      return $this->_get(1013);
    }
    
    /**
     * Set <include_item_no_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setIncludeItemNoNull( $value){
      return $this->_set(1013, $value);
    }
    
    /**
     * Check if <order_desc> has a value
     *
     * @return boolean
     */
    public function hasOrderDesc(){
      return $this->_has(14);
    }
    
    /**
     * Clear <order_desc> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderDesc(){
      return $this->_clear(14);
    }
    
    /**
     * Get <order_desc> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getOrderDesc(){
      return $this->_get(14);
    }
    
    /**
     * Set <order_desc> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderDesc(\dstore\engine\values\booleanValue $value){
      return $this->_set(14, $value);
    }
    
    /**
     * Check if <order_desc_null> has a value
     *
     * @return boolean
     */
    public function hasOrderDescNull(){
      return $this->_has(1014);
    }
    
    /**
     * Clear <order_desc_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearOrderDescNull(){
      return $this->_clear(1014);
    }
    
    /**
     * Get <order_desc_null> value
     *
     * @return boolean
     */
    public function getOrderDescNull(){
      return $this->_get(1014);
    }
    
    /**
     * Set <order_desc_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setOrderDescNull( $value){
      return $this->_set(1014, $value);
    }
    
    /**
     * Check if <information_type_id> has a value
     *
     * @return boolean
     */
    public function hasInformationTypeId(){
      return $this->_has(15);
    }
    
    /**
     * Clear <information_type_id> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearInformationTypeId(){
      return $this->_clear(15);
    }
    
    /**
     * Get <information_type_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getInformationTypeId(){
      return $this->_get(15);
    }
    
    /**
     * Set <information_type_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setInformationTypeId(\dstore\engine\values\integerValue $value){
      return $this->_set(15, $value);
    }
    
    /**
     * Check if <information_type_id_null> has a value
     *
     * @return boolean
     */
    public function hasInformationTypeIdNull(){
      return $this->_has(1015);
    }
    
    /**
     * Clear <information_type_id_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearInformationTypeIdNull(){
      return $this->_clear(1015);
    }
    
    /**
     * Get <information_type_id_null> value
     *
     * @return boolean
     */
    public function getInformationTypeIdNull(){
      return $this->_get(1015);
    }
    
    /**
     * Set <information_type_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setInformationTypeIdNull( $value){
      return $this->_set(1015, $value);
    }
    
    /**
     * Check if <information> has a value
     *
     * @return boolean
     */
    public function hasInformation(){
      return $this->_has(16);
    }
    
    /**
     * Clear <information> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearInformation(){
      return $this->_clear(16);
    }
    
    /**
     * Get <information> value
     *
     * @return \dstore\engine\values\stringValue
     */
    public function getInformation(){
      return $this->_get(16);
    }
    
    /**
     * Set <information> value
     *
     * @param \dstore\engine\values\stringValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setInformation(\dstore\engine\values\stringValue $value){
      return $this->_set(16, $value);
    }
    
    /**
     * Check if <information_null> has a value
     *
     * @return boolean
     */
    public function hasInformationNull(){
      return $this->_has(1016);
    }
    
    /**
     * Clear <information_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearInformationNull(){
      return $this->_clear(1016);
    }
    
    /**
     * Get <information_null> value
     *
     * @return boolean
     */
    public function getInformationNull(){
      return $this->_get(1016);
    }
    
    /**
     * Set <information_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setInformationNull( $value){
      return $this->_set(1016, $value);
    }
    
    /**
     * Check if <node_characteristic_id> has a value
     *
     * @return boolean
     */
    public function hasNodeCharacteristicId(){
      return $this->_has(17);
    }
    
    /**
     * Clear <node_characteristic_id> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearNodeCharacteristicId(){
      return $this->_clear(17);
    }
    
    /**
     * Get <node_characteristic_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getNodeCharacteristicId(){
      return $this->_get(17);
    }
    
    /**
     * Set <node_characteristic_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setNodeCharacteristicId(\dstore\engine\values\integerValue $value){
      return $this->_set(17, $value);
    }
    
    /**
     * Check if <node_characteristic_id_null> has a value
     *
     * @return boolean
     */
    public function hasNodeCharacteristicIdNull(){
      return $this->_has(1017);
    }
    
    /**
     * Clear <node_characteristic_id_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearNodeCharacteristicIdNull(){
      return $this->_clear(1017);
    }
    
    /**
     * Get <node_characteristic_id_null> value
     *
     * @return boolean
     */
    public function getNodeCharacteristicIdNull(){
      return $this->_get(1017);
    }
    
    /**
     * Set <node_characteristic_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setNodeCharacteristicIdNull( $value){
      return $this->_set(1017, $value);
    }
    
    /**
     * Check if <language_id> has a value
     *
     * @return boolean
     */
    public function hasLanguageId(){
      return $this->_has(18);
    }
    
    /**
     * Clear <language_id> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearLanguageId(){
      return $this->_clear(18);
    }
    
    /**
     * Get <language_id> value
     *
     * @return \dstore\engine\values\integerValue
     */
    public function getLanguageId(){
      return $this->_get(18);
    }
    
    /**
     * Set <language_id> value
     *
     * @param \dstore\engine\values\integerValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setLanguageId(\dstore\engine\values\integerValue $value){
      return $this->_set(18, $value);
    }
    
    /**
     * Check if <language_id_null> has a value
     *
     * @return boolean
     */
    public function hasLanguageIdNull(){
      return $this->_has(1018);
    }
    
    /**
     * Clear <language_id_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearLanguageIdNull(){
      return $this->_clear(1018);
    }
    
    /**
     * Get <language_id_null> value
     *
     * @return boolean
     */
    public function getLanguageIdNull(){
      return $this->_get(1018);
    }
    
    /**
     * Set <language_id_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setLanguageIdNull( $value){
      return $this->_set(1018, $value);
    }
    
    /**
     * Check if <purchase_order> has a value
     *
     * @return boolean
     */
    public function hasPurchaseOrder(){
      return $this->_has(19);
    }
    
    /**
     * Clear <purchase_order> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPurchaseOrder(){
      return $this->_clear(19);
    }
    
    /**
     * Get <purchase_order> value
     *
     * @return \dstore\engine\values\booleanValue
     */
    public function getPurchaseOrder(){
      return $this->_get(19);
    }
    
    /**
     * Set <purchase_order> value
     *
     * @param \dstore\engine\values\booleanValue $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPurchaseOrder(\dstore\engine\values\booleanValue $value){
      return $this->_set(19, $value);
    }
    
    /**
     * Check if <purchase_order_null> has a value
     *
     * @return boolean
     */
    public function hasPurchaseOrderNull(){
      return $this->_has(1019);
    }
    
    /**
     * Clear <purchase_order_null> value
     *
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function clearPurchaseOrderNull(){
      return $this->_clear(1019);
    }
    
    /**
     * Get <purchase_order_null> value
     *
     * @return boolean
     */
    public function getPurchaseOrderNull(){
      return $this->_get(1019);
    }
    
    /**
     * Set <purchase_order_null> value
     *
     * @param boolean $value
     * @return \dstore\engine\om_GetOrders_Pu\Parameters
     */
    public function setPurchaseOrderNull( $value){
      return $this->_set(1019, $value);
    }
  }
}

