<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dstore/engine/procedures/im_InsertNodeSymbol_Ad.proto

namespace Dstore\Engine\Im_InsertNodeSymbol_Ad;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>dstore.engine.im_InsertNodeSymbol_Ad.Parameters</code>
 */
class Parameters extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.dstore.values.IntegerValue symbol_id = 1;</code>
     */
    private $symbol_id = null;
    /**
     * <code>bool symbol_id_null = 1001;</code>
     */
    private $symbol_id_null = false;

    public function __construct() {
        \GPBMetadata\Dstore\Engine\Procedures\ImInsertNodeSymbolAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>.dstore.values.IntegerValue symbol_id = 1;</code>
     */
    public function getSymbolId()
    {
        return $this->symbol_id;
    }

    /**
     * <code>.dstore.values.IntegerValue symbol_id = 1;</code>
     */
    public function setSymbolId(&$var)
    {
        GPBUtil::checkMessage($var, \Dstore\Values\IntegerValue::class);
        $this->symbol_id = $var;
    }

    /**
     * <code>bool symbol_id_null = 1001;</code>
     */
    public function getSymbolIdNull()
    {
        return $this->symbol_id_null;
    }

    /**
     * <code>bool symbol_id_null = 1001;</code>
     */
    public function setSymbolIdNull($var)
    {
        GPBUtil::checkBool($var);
        $this->symbol_id_null = $var;
    }

}

